### ISSUE TITLE
fix: Invalid JS call result type '3' in pageload

### ISSUE THREAD

**Issue by MvandeRuitenbeek** [microsoft/fast-blazor#109]
# 🐛 Bug Report

Blazor Page does not load after updating to version 0.5.0 in Blazor WASM

## 💻 Repro or Code Sample

Create new project, add the repo version 0.5.0 via NuGet and add the javascript snippet in index.html. Fluent components not yet used, only installed the package

## 🤔 Expected Behavior

Running the application should open the page

## 😯 Current Behavior

Page does not load. Instead, the console output says:
blazor.webassembly.js:1 Uncaught (in promise) Error: Invalid JS call result type '3'.
    at _ (blazor.webassembly.js:1)
    at blazor.webassembly.js:1

## 🌍 Your Environment

* OS & Device: Windows
* Browser Microsoft Edge, Google Chrome
* .NET 6 preview and FAST Version 0.5.0

**Comment by EisenbergEffect** [comment]
New release for .NET 6 is out.
