### ISSUE TITLE
feat: add [culture specific formatting and thousand separator] to/in [FluentNumberField]

### ISSUE THREAD

**Issue by Ciwo-K** [microsoft/fast-blazor#113]
# 🙋 Feature Request

I'd like to be able to set a culture specific format for FluentNumberField as a parameter in the component. 
The components should also take into account the settings of the app. -> `app.UseRequestLocalization("de-DE");` 

## 🤔 Expected Behavior

After the culture info is set to (de-DE), the component should have a point as a thousand separator and a comma as a comma separator.

![image](https://user-images.githubusercontent.com/62892625/140373647-a1f5ae0e-86b2-4077-b750-c9b6e5b92263.png)
[CultureInfo.CreateSpecificCulture("de-DE")]

## 😯 Current Behavior

At the moment there is neither the thousands separator nor the option to set the culture info.
![image](https://user-images.githubusercontent.com/62892625/140373607-fff93a90-6ab0-42d5-b88b-999b473a96bd.png)
[CultureInfo.InvariantCulture]

## 🔦 Context

I would like to use the NumberTextField component in German localization. Long numbers difficult to read without the thousand separator.

**Comment by EisenbergEffect** [comment]
I'm not sure if this is something we need to do at the web component level or just in Blazor or both. @chrisdholt How is our number input handling this scenario today in pure JS/HTML?

**Comment by vnbaaij** [comment]
I did some research and it is just not possible to do this with an `<input type="number">`. Chrome uses the Browser setting, Firefox doesn't. At least not always - e.g. when there is a lang attribute in the <html> tag, Firefox uses this.

See also https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/ for some background information on when not to use a number input
