### ISSUE TITLE
fix: [bind-Value not working] in [FluentNumberField]

### ISSUE THREAD

**Issue by Ciwo-K** [microsoft/fast-blazor#115]
# 🐛 Bug Report

At the moment it seems it is not possible to bind to a FluentNumberField via `@bind-Value=...`.

## 💻 Repro or Code Sample

Go to example page -> Blazor component bindings -> enter a number into the 'Number field Value' input box. The value is not being updated. 
The FluentTextField above (Text field Value) is being updated properly.

## 🤔 Expected Behavior

The component should bind to the value and update it.

## 😯 Current Behavior

The bound value is not being updated.
![image](https://user-images.githubusercontent.com/62892625/140487123-a8bb4221-3831-442c-b947-75aef79c331e.png)
[FluentTextField binds correctly while FluentNumberField does not]

## 🌍 Your Environment

Windows 10, Chrome, fast-blazor (version 0.4)

**Comment by vnbaaij** [comment]
That is fixed in 0.5.0
