### ISSUE TITLE
Data-binding with Checked in FluentCheckbox and FluentSwitch doesn't work.

### ISSUE THREAD

**Issue by robertsundstrom** [microsoft/fast-blazor#131]
I assumed that you could do a two-way binding to the ```Checked``` property (```@bind-Checked```) in FluentCheckbox and FluentSwitch. That seemed the most logical - but it did not work. So I tried ```@bind-Value``` instead, and then all good.

What is the reason for this? Is it just because of the shared base using ```Value``` instead.

**Comment by vnbaaij** [comment]
Yes, that is of the shared base using `Value`

**Comment by robertsundstrom** [comment]
@vnbaaij OK. That was a bit confusing. ```Checked``` is more semantic.

MudBlazor binds using ```@bind-Checked``` for its Toggle control. It also works for ```EditForm```.

I would be more comfortable if both propeties were allowed for data-binding.

**Comment by vnbaaij** [comment]
`Checked` is more semantic yes, but we are following the ASP.NET Core InputCheckbox implementation that also (only) uses`Value`. 
I can see if `Checked` can be added in a future version.

> It also works for `EditForm`.

Not really sure what you mean here. FluentCheckbox and FluentSwitch work with `EditFrom` as well...

**Comment by robertsundstrom** [comment]
@vnbaaij OK. I'm new to Fluent UI.

> Not really sure what you mean here. FluentCheckbox and FluentSwitch work with EditFrom as well...

I actually assumed it worked from looking around. Just pointed out that I thought MudBlazor was more semantic in this regard.

**Comment by robertsundstrom** [comment]
To add, I was looking in the sample pages where ```Checked``` is used. So that is why I initially assumed it was bindable. 

That was the reason for the surprise.
