### ISSUE TITLE
docs: Please consider adding XML documentation for Fluent razor components

### ISSUE THREAD

**Issue by ShreyasJejurkar** [microsoft/fast-blazor#134]
# 🙋 Documentation Request
Please consider adding XML documentation for C# blazor component API. 
Consider the following scenario, how come newcomers know what needs to be used for rendering anchor tags, as they see two components here. 

![image](https://user-images.githubusercontent.com/17148381/142764451-af2d5bf6-a7c2-4683-9b48-564ab21b0778.png)

If we compare this with inbuilt blazor components, at least we get some component information while typing itself. 

![image](https://user-images.githubusercontent.com/17148381/142764478-e12295c4-a084-42c1-bbae-4a724df83695.png)

## 💁 Possible Solution
We should consider adding XML documentation for these components and as well as their individual properties, as these comments can be inferred by Visual Studio and Visual Studio Code and provide a great experience for developers!

I am ready to help with this task to get it complete😅. But filling issue first so that we can track progress and I can know other people's thoughts on it if I miss anything here!

**Comment by ShreyasJejurkar** [comment]
@EisenbergEffect Yes. 
Can I know the place where we keep docs for FAST UI components so that I will try to match docs with their docs about each property and component so that it will be consistent for users!

**Comment by vnbaaij** [comment]
@ShreyasJejurkar 
The official docs are here: https://docs.microsoft.com/en-us/fluent-ui/web-components/
The Fluent UI Web Components source is here: https://github.com/microsoft/fluentui/tree/master/packages/web-components

**Comment by ShreyasJejurkar** [comment]
Thanks, @vnbaaij. I will start working on this one-by-one component this upcoming weekend.

**Comment by ShreyasJejurkar** [comment]
@vnbaaij Hmm. Yeh. That would be a good idea to have a separate file for code-behind `.razor.cs`. Right now the code is small so it's ok, but going forward it can be huge so better to go off with code-behind. 
Am totally ok with that approach. 👍

**Comment by ShreyasJejurkar** [comment]
@EisenbergEffect Yup.

@vnbaaij 's namespace PR - > moving it to `razor.cs` - > xml docs!

**Comment by vnbaaij** [comment]
@EisenbergEffect If you canget #126 in first, I'll post another PR to move the code to separate files, update usings, etc in a bit

**Comment by EisenbergEffect** [comment]
#126 is now merged 😄 (I really like the new using and namespace features.)

**Comment by ShreyasJejurkar** [comment]
@EisenbergEffect yup, that feature is quite good one!

**Comment by vnbaaij** [comment]
@EisenbergEffect #138 is ready for merging the changes mentioned above

**Comment by vnbaaij** [comment]
Closed with #188
