### ISSUE TITLE
rfc: Track blazor wrappers for fast components

### ISSUE THREAD

**Issue by ShreyasJejurkar** [microsoft/fast-blazor#135]
# 💬 RFC
We should consider creating a tracker sheet to track progress or to highlight for which fast components do we have blazor wrappers. If for some fast components we don't have wrappers as of now we can mention there, so that community can see the progress of the fast-blazor library. In this way, developers and the community can have a clear picture of what's there and what's not. 

## 💻 Examples
We can track progress and availability with tables of the following columns. 
Columns - 
1. fast component name 
2. blazor fast component name
3. Complete or not (with checkbox)
4. Remarks - This column if some property on the fast component is not yet available in razor component. 

I had this motivation from looking at how the dotnet maui team is tracking progress. 
https://github.com/dotnet/maui/wiki/Status

**Comment by vnbaaij** [comment]
Good idea, but we are following the Fluent Web Controls here which are not always 100% in line with the Fast components

**Comment by ShreyasJejurkar** [comment]
yeah. So we can track blazor components progress against Fast web components!

**Comment by vnbaaij** [comment]
No, we can track against the Fluent web components (https://github.com/microsoft/fluentui/tree/master/packages/web-components)

**Comment by ShreyasJejurkar** [comment]
Ohhh. Names got me confused. So this is the track I guess. 

Fluent web components --> Fast web components --> blazor fast web components (.razor)

Is my understanding and sequence right?

**Comment by vnbaaij** [comment]
Almost 😁
First there is Fast framework with it's own Fast WC implementation. Then Fluent WC (following the Fluent Design) are another implementation of Fast. These Fluent web components are the components we are wrapping with Blazor here.

**Comment by ShreyasJejurkar** [comment]
Ahh naming is hard.
So we can track progress against fluent web components for our blazor web components right?

**Comment by EisenbergEffect** [comment]
Ok, so to clarify, we'll add a markdown document with a table that has the following columns:

1. FluentUI Web Component name
2. Blazor component name
3. Complete or not (with checkbox)
4. Remarks - This column if some property on the fast component is not yet available in razor component.

Should we also add some links for convenience? For example: link to the Blazor component example, link to the docs.microsoft.com page for the component, etc.

**Comment by ShreyasJejurkar** [comment]
> Should we also add some links for convenience? For example link to the Blazor component example, link to the docs.microsoft.com page for the component, etc.

Hmm, that would be a good idea as well. But on the docs website, there are no samples regarding blazor components, I have seen samples for typescript only. https://docs.microsoft.com/en-us/fluent-ui/web-components/components/badge
