### ISSUE TITLE
rfc: using `Enum.ToString().ToLowerInvariant()` instead of current `ToAttributeValue` hack. 

### ISSUE THREAD

**Issue by ShreyasJejurkar** [microsoft/fast-blazor#136]
# 💬 RFC
A better and simple approach for getting enum underlying value.

## 🔦 Context
Right now all over the codebase, we are using the Enum extension method `ToAttributeValue()` to get passed enum value in a string format in lower case. If we see implementation, this results in the static dictionary in memory, which will last till the application runs and GC will not collect it as it's static. 
Not sure, why this approach has been used. Whereas we can get enum value directly by doing `<enum_variable>.ToString()..ToLowerInvariant().` This approach is quite simple and straight forward and we can avoid this extension methods for enum and can save memory footprint. 

## 💻 Examples
A small example I created about usage.  https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWAChiA3CZAAgkoF5KBxAUxgBMnkA6AWQgBsmAbmLEseAJwAKCJwAqAewDKCZLADmkgJRz5AGXkB3DgEkY5VRBgItm4SSJYAzJRaowjFuyoBvYpX+UvAJwlH4BAGJMkALEAL5AA===

Usage in code (see appearance attribute value)

![image](https://user-images.githubusercontent.com/17148381/142766884-66bf6cd8-e6f7-4586-9976-dc4e5b95b44c.png)

**Comment by EisenbergEffect** [comment]
This was the approach the Blazor team recommended. So, I'll have to defer to them for feedback. /cc @javiercn

**Comment by javiercn** [comment]
I don't think the proposed change is beneficial.

The memory allocated by the dictionaries won't significantly impact the memory footprint of the app and on the contrary the proposed alternative will generate a lot of short-lived object that will dramatically increase GC pressure.

I don't think we should make any change here unless there is conclusive performance data that justifies it.

**Comment by EisenbergEffect** [comment]
Closing this for now based on feedback from @javiercn .
