### ISSUE TITLE
docs: add final example for FluentDesignSystemProvider to Blazor WASM

### ISSUE THREAD

**Issue by hkusulja** [microsoft/fast-blazor#139]
Can you please update documentation - https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/docs/integrations/blazor.md

in case when using blank new project with .NET 6, Blazor, WebAssembly, like:
dotnet new blazorwasm

How to properly integrate FluentDesignSystemProvider tag into wwwroot/index.html and Pages/Index.razor and Shared/MainLayour.razor . Maybe create better dotnet template for starters, so instead of default blazorwasm to use something like fast-blazor project as a starter.

Reference for custom dotnet project template - https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-project-template

**Comment by hkusulja** [comment]
ok, thank you for reference for new dotnet template.
In mean time, if you can also update here / FAST documentation about Blazor page and usage with clarification about mentioned <FluentDesignSystemProvider> and its location (which file) needs to be put in new / empty project created with default template dotnet new blazorwasm

**Comment by vnbaaij** [comment]
Hi @hkusulja, love the template idea. Pretty sure that will be picked up. In the meantime, I think you can find the instructions you need in the [readme.md](https://github.com/microsoft/fast-blazor/blob/main/README.md) file of this repo

**Comment by hkusulja** [comment]
@vnbaaij The mentioned readme.md is not clear where (which file / line) to put <FluentDesignSystemProvider>  ...

**Comment by vnbaaij** [comment]
If you follow https://github.com/microsoft/fast-blazor/blob/main/README.md#configuring-the-design-system, there is only one file in your project that you need to change (besides adding the `<script>` to the index.html in a wasm app) and that is `App.razor'. You replace the entire contents of the file with what is shown in the code block.

**Comment by hkusulja** [comment]
Ok, can you update then documentation saying that "Example App.razor file looks like" ...

**Comment by vnbaaij** [comment]
Will do!
