### ISSUE TITLE
FluentDataGrid - Add Custom Column Header and Sort By It

### ISSUE THREAD

**Issue by grumpykiwi** [microsoft/fast-blazor#143]
Hi

I am experimenting with the Fast Blazor datagrid component and want to be able to add custom column names and make them sortable. I dont see anything in the samples or a search on how to do that. Below is my grid definition

```
    <FluentDataGrid id="defaultGrid3"
                RowsData=GroupUsers
                ColumnDefinitions=ColumnsGrid1
                GridTemplateColumns="1fr 1fr 1fr 1fr 1fr 1fr">
        <HeaderCellTemplate>
            
        </HeaderCellTemplate>
        <RowItemTemplate>
            <FluentDataGridRow TItem=string RowType="DataGridRowType.Header">
                <FluentDataGridCell GridColumn=1 CellType="DataGridCellType.ColumnHeader">Name</FluentDataGridCell>
                <FluentDataGridCell GridColumn=2 CellType="DataGridCellType.ColumnHeader">Email</FluentDataGridCell>
                <FluentDataGridCell GridColumn=3 CellType="DataGridCellType.ColumnHeader">Title</FluentDataGridCell>
                <FluentDataGridCell GridColumn=4 CellType="DataGridCellType.ColumnHeader">Location</FluentDataGridCell>
                <FluentDataGridCell GridColumn=5 CellType="DataGridCellType.ColumnHeader">Status</FluentDataGridCell>
                <FluentDataGridCell GridColumn=6 CellType="DataGridCellType.ColumnHeader">Phone</FluentDataGridCell>
            </FluentDataGridRow>
            <FluentDataGridRow TItem=GroupUser>
                <FluentDataGridCell GridColumn=1>@context.DisplayName</FluentDataGridCell>
                <FluentDataGridCell GridColumn=2>
                    <a href="mailto:@context.UserPrincipalName">@context.UserPrincipalName</a>
                </FluentDataGridCell>
                <FluentDataGridCell GridColumn=3>@context.JobTitle</FluentDataGridCell>
                <FluentDataGridCell GridColumn=4>@context.OfficeLocation</FluentDataGridCell>
                <FluentDataGridCell GridColumn=5>@context.Status</FluentDataGridCell>
                <FluentDataGridCell GridColumn=6>@context.OfficeFaxPhone</FluentDataGridCell>
            </FluentDataGridRow>
        </RowItemTemplate>
    </FluentDataGrid>

```
Currently, the titles get repeated for each data row. See attached for example

Thanks

Mark

![Fast Grid](https://user-images.githubusercontent.com/43825887/146704101-23e58480-09a4-4946-9c46-cf4e69e20a4b.png)

**Comment by vnbaaij** [comment]
Hi,
The Row template specifies how each row should be built up. As you put the titles in there, they are show on each row as to be expected. What you want to do is to move the specification of the titles to a separate list and then use the `HeaderCellTemplate`
An example with custom names and sorting can be found in the `DataGrid` demo page [here](https://github.com/microsoft/fast-blazor/blob/a8b5da3518a71853f8f82ed198067197bb1e5bd0/examples/FluentUI.Demo.Shared/Pages/DataGridPage.razor?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L38
)

**Comment by grumpykiwi** [comment]
That did it thanks. Although I might add the Blazorise Datagrid is a lot easier to use, and very well documented. I should not have to hunt down what I asked for.

I went back to Blazorise. Not worth the hassle.


Mark Nash
Senior Software Engineer        [cid:PC_42x23_fbb4e57e-65d2-4c41-b09e-ffa9f4a3c468.png]

PartnerComm, Inc.
Winner of 76 IABC Gold Quills
2021 Large Agency of the Year
2304 W Interstate 20, Suite 250
Arlington, TX 76017
        [cid:pcomm25+_471933a4-f842-490b-84d4-910cf0397a29.png]

Office: (817) 465-9277
***@***.***
www.partnercomm.net<http://www.partnercomm.net>





This e-mail transmission may contain confidential information or may be otherwise legally privileged. If you are not the intended recipient you are hereby notified that any use, disclosure, copying, forwarding, or distribution of any of the information contained in or attached to this message is STRICTLY PROHIBITED.

________________________________
