### ISSUE TITLE
fix: two key strokes required to change item in FluentSelect

### ISSUE THREAD

**Issue by majkada** [microsoft/fast-blazor#1448]
# 🐛 Bug Report

While using a FluentSelect with a keyboard 2 key strokes (either arrow up or arrow down) are required to actually change an item.

## 💻 Repro or Code Sample

E.g. it can be reproduced on https://www.fluentui-blazor.net/Forms with the "Primary Classification" select.

## 🤔 Expected Behavior

Only one key stroke is required to change an item.

## 😯 Current Behavior

Exactly two key strokes are required.

* OS & Device: Windows on PC
* Browser Google Chrome
* FluentUI 4.4.0

**Comment by vnbaaij** [comment]
The strange thing is this only happens in WASM and it is not necessary for every item in a select. Even stranger is that if you add an `fluent-select` web component, it does work as expected. On Server it works with one keypress regardless.

I'll leave this open, but as the impact is really low and the component works as it should , we won't prioritize finding a solution for it.

**Comment by vnbaaij** [comment]
Ok, Adding that delay for the next release 4.4.1.
