### ISSUE TITLE
No way to focus a Fluent component

### ISSUE THREAD

**Issue by ameyasubhedar** [microsoft/fast-blazor#157]
The components need a way to focus on the underlying element. When validation fails, the UX system can highlight the error component.

E.g. 

FluentUI components should have IFocusable that defines whether an element can receive Focus and the FocusAsync method to focus the underlying element. Blazor supports this via @ref ElementReference, FieldIdentifier and the Focus method. 

I need a similar way for FluentUI components. There are a lot of use cases where programmatic Focus is required.
 
Example Use Case:

Delete UI, 
`FluentInputText -> FluentInputBase<string>`
System ask user to enter a confirmation value
User enters an incorrect value
Form Submit

There is no way for the UX system to focus on the FluentInputText with an incorrect value.

**Comment by vnbaaij** [comment]
@EisenbergEffect Not yet, but I'll take a look!
