### ISSUE TITLE
fix: Color is distorted in FluentDesignTheme

### ISSUE THREAD

**Issue by chrischu** [microsoft/fast-blazor#1609]
# 🐛 Bug Report

When setting a color via `FluentDesignTheme` it seems to be oddly distorted for certain colors.

## 💻 Repro or Code Sample

Create a new project via `dotnet new fluentblazor -o Fluent` and add the following line:
```
<FluentDesignTheme OfficeColor="OfficeColor.PowerBI" Mode="DesignThemeModes.Light" />
```
to the App.razor file

## 🤔 Expected Behavior

The resuling color should be like it is described in the documentation (https://fluent2.microsoft.design/color#brand-colors):
![image](https://github.com/microsoft/fluentui-blazor/assets/447251/3e16cca8-ed9b-46bc-9fe3-a85bb2acd2c0).

## 😯 Current Behavior

The color looks like this:
![image](https://github.com/microsoft/fluentui-blazor/assets/447251/ab4595fb-3239-47cf-b6c1-2511229e096e)

## 🔦 Context

I would like to use a bright yellow as the primary color in my application, but cannot seem to get it to work (I also tried deliberately using a "lighter" yellow to see if I can get a more acceptable output color but nothing seems to work :(.

## 🌍 Your Environment

* Windows 11, PC
* Mozilla Firefox & Google Chrome
* .NET 8.0.2 and Fluent UI Blazor library Version 4.4.1

**Comment by chrischu** [comment]
Then the problem is maybe that there is no way to adjust any of the settings in a way to allow a yellow primary color (e.g. by changing the text color to be black instead of white and achieving the necessary contrast that way) maybe?

**Comment by chrischu** [comment]
Also interestingly enough if I try to explore the color options with https://color.fast.design/ and use (FFFF00) I don't get that ugly brown color.

**Comment by vnbaaij** [comment]
> Also interestingly enough if I try to explore the color options with https://color.fast.design/ and use (FFFF00) I don't get that ugly brown color.

As explained in the comment I linked earlier, that one is using an earlier version of the color system

**Comment by chrischu** [comment]
I'm confused first you say the docs you linked are for Fluent 2 and the web components I'm using are still using Fluent 1 (presumable older than Fluent 2).
> The link you are mentioning is for Fluent 2. At the moment (because we are using the Fluent UI Web Components implementation) we are still at Fluent 1

Then your saying that the link refers to an earlier version of the color system?
> As explained in the comment I linked earlier, that one is using an earlier version of the color system

So either https://color.fast.design/ uses a version previous to Fluent 1 or I'm misunderstanding something.

**Comment by vnbaaij** [comment]
> Then the problem is maybe that there is no way to adjust any of the settings in a way to allow a yellow primary color (e.g. by changing the text color to be black instead of white and achieving the necessary contrast that way) maybe?
Not for the accent color used in the components, no. Sorry but that is just how the system works at the moment.

**Comment by chrischu** [comment]
Ok just to be clear: which version of Fluent is https://color.fast.design/ using?

**Comment by vnbaaij** [comment]
You linked to Fluent 2 docs, but we  are not using Fluent 2 yet. We use the Fluent UI Web Components implementation which still uses Fluent 1 Design System. 
Fluent 1 uses the Adaptive Color System which you can see in action here https://fluent-components.azurewebsites.net/?path=/docs/design-system-color-explorer--page (from the comment on the other issue I linked to). color.fast.design is not using Fluent at all. It is using an older version of the Adaptive Color System.

Soryy. Hope that makes it more clear. I know it is confusing to have all those version and tems intermingled but it is out of our hands and control...

**Comment by chrischu** [comment]
Oh ok, yeah it really is a bit confusing, but I get that that is out of your control. Thanks for the explanation and the quick replys!

**Comment by chrischu** [comment]
So essentially the Fluent 1 color system does not really look great with light accent colors :(.
