### ISSUE TITLE
feat: update configuration to deploy readme.md

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast-blazor#166]
# 🙋 Feature Request
When publishing .NET Templates, a configuration update is required in order to automatically include the readme.md documentation during the push to NuGet.org.  For [reference](https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/).

## 🤔 Expected Behavior
Deploy readme.md as package template root readme.

## 😯 Current Behavior
Requires manual upload from `*.csproj\readme.md` 

## 💁 Possible Solution
Update `.nuspec` or `.csproj` or other files to configure appropriately.

**Comment by vnbaaij** [comment]
This is automatically done through the `.nuspec` files
