### ISSUE TITLE
feat: add badges for Components and Templates

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast-blazor#172]
# 🙋 Feature Request
* Update the Readme.md file with a new name "Component Library" for NuGet Package
* Add new badge for NuGet "Templates"

## 🤔 Expected Behavior
The name and version should display on the readme.

## 😯 Current Behavior
Lists build number for Components fine, but does not have one for Templates.

**Comment by MACEL94** [comment]
Hello @awentzel 

Do you have any hints on how do you expect this feature to be implemented?
I'm willing to work on this, I'd be happy to learn and help :)

**Comment by vnbaaij** [comment]
Hi @MACEL94,

Thanks for your offer, but it is already done. Was just a matter of attaching a `?label=...` to the shield URLs
