### ISSUE TITLE
In version 1.4.0 the datagrid header cell template displays the column headers incorrectly

### ISSUE THREAD

**Issue by chigivigi** [microsoft/fast-blazor#182]
# 🐛 Bug Report

In version 1.4.0 the datagrid components header cell template values are displayed incorrectly. They are squished together and are not in line with their columns 

## 💻 Repro or Code Sample

Create a simple datagrid template and set the header cell template:

```
<HeaderCellTemplate>
        <FluentButton @onclick=@(()=>SortColumn(context))>
            @context.Title
            @if (context.Title == lastSortColumn?.Title)
            {
                @(isAscending ? " ↑" : " ↓")
            }
        </FluentButton>
    </HeaderCellTemplate>
```

## 🤔 Expected Behavior

The header should be inline with their columns.

It works fine in version 1.2.1.

![image](https://user-images.githubusercontent.com/30351793/166911268-179ea716-f3d4-4a5f-9ad5-6ae090bb81f5.png)

## 😯 Current Behavior

![image](https://user-images.githubusercontent.com/30351793/166910528-035802a6-47d3-4cb8-af3f-e964310a8ab0.png)

## 💁 Possible Solution

I do not know what is wrong but it works fine in version 1.2.1.

## 🔦 Context

It is harder to work when the header cell are squished together, It is hared to sort the fields.

## 🌍 Your Environment

Windows 10
Microsoft Edge
Version 101.0.1210.32 (Official build) (64-bit)

**Comment by TravisSpomer** [comment]
I'm seeing this too. If you inspect the headers in the browser dev tools, you can see that Blazor component markup is being sent to the browser so it's not rendering properly.

```html
<fluentdatagridrow rowtype="Header" titem="TItem">
  <fluentdatagridcell gridcolumn="1" celltype="DataGridCellType.ColumnHeader">
```
