### ISSUE TITLE
fix: Unable to change the size of Switch control 

### ISSUE THREAD

**Issue by svetovid** [microsoft/fast-blazor#1820]
# 🐛 Unable to change the size of Switch control

We need to increase the size of the control, so it's touch friendly. Or, in general, it must be possible to make controls bigger by changing font size.
Unfortunately, I couldn't find an acceptable mechanism of doing this. 
There is `--base-height-multiplier` variable but even when I override it, SVG element inside <fluent-switch> keeps its initial size

## 💻 Repro or Code Sample

```
 <FluentSwitch @bind-Value="@State" CheckedMessage="On" UncheckedMessage="Off" Required />
```

## 🤔 Expected Behavior

SVG elements in controls can be changed with variables, or it's possible to access to them from within a custom CSS.

## 😯 Current Behavior

Changing `--base-height-multiplier` variable, SVG element keeps its initial size

## 🌍 Your Environment

* Windows
* Microsoft Edge
* .NET 8.0.0
* Microsoft.FluentUI.AspNetCore.Components 4.5.0

![fluent-switch_bug](https://github.com/microsoft/fluentui-blazor/assets/9212389/dad4df9e-acd7-446d-8609-c48ee1b5fa57)

**Comment by vnbaaij** [comment]
I also changed the --density var and the width/height of the SVG. Gives me this (only for the 'new feature' one):

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/7a92bf18-8a9d-48dc-adaa-8536df639742)

**Comment by c0g1t8** [comment]
@svetovid 

I'm not sure if this will help. I used CSS to scale the Switch control in my responsize web applications.  I used media-queries to change the scale size.

Bascially, it was something like:
``` razor
<div class="box">
    <div style="transform: scale(2); transform-origin: left top;">
        <FluentSwitch @bind-Value=@value Label="New Feature">
            <span slot="checked-message">On</span>
            <span slot="unchecked-message">Off</span>
        </FluentSwitch>
    </div>
</div>
```
The primary thing to consider is that scaled items do not affect layout. The layout does not change to account for the change in the scaled elements. In my case, I created a fixed `box` size for layout purposes and then placed the switch within it.

**Comment by svetovid** [comment]
Thank you, @c0g1t8 
But I would prefer to have static CSS properties like width/height. 
Ideally, the component must know how to scale automatically, basing on a CSS variable.

**Comment by vnbaaij** [comment]
Ideally it would indeed. From what I've found though, the size of the svg is hardcoded in the style of the `fluent-switch` web component we wrap. Please raise an issue over there to see if they can cange it.

**Comment by c0g1t8** [comment]
@svetovid 

@vnbaaij comments made me take another look.  If you wish to do this in static CSS properties, consider the following:

``` razor
<style>
    fluent-switch::part(switch) {
        --switch-scale: 2;
        transform: scale(var(--switch-scale));
        margin: calc(10px * (var(--switch-scale) - 1)) calc(20px * (var(--switch-scale) - 1))
    }
</style>

<div>
    <FluentSwitch @bind-Value=@value Label="New Feature">
        <span slot="checked-message">On</span>
        <span slot="unchecked-message">Off</span>
    </FluentSwitch>
</div>
```
This approach targets the underlying `fluent-switch` implementation directly. Only the size of the switch itself is changed. The label and text are not. It also has the added benefit of not requiring you to make any markup changes.

**Comment by svetovid** [comment]
@c0g1t8 , I modified a bit your solution by `--base-height-multiplier: 8;` because I already used this variable to increase other controls
```
fluent-switch::part(switch) {
  --base-height-multiplier: 8;
  --switch-scale: 1.25;
  transform: scale(var(--switch-scale));
  margin: calc(10px*(var(--switch-scale) - 1)) calc(20px*(var(--switch-scale) - 1));
} 
```
and now it works for me!

But still, it's a dirty hack! ;)
I'd rather use a proper solution out-of-the-box instead of overriding variables and using transform.

For now we will use this solution.
Please, ping me once it's fixed

Thank you!

**Comment by c0g1t8** [comment]
@svetovid 

I'm happy you were able to make use of my _hack_. It is highly dependent on knowledge of the underlying implementation provided by the [fluentui libarary](https://github.com/microsoft/fluentui). Any changes there may break this _hack_.

IMO - I would not make this change to this library. This library is primarily a wrapper around the [fluentui libarary](https://github.com/microsoft/fluentui) and straying to far away from this intent could have larger ramifications in the future such as an implementation change in a wrapped component. A behavioural change to wrapped component needs/should be addressed at the source.

BTW - your rationale with regards to the implied reason for `--base-height-multiplier` is not flawed.
