### ISSUE TITLE
fix: double and float decimals not showing up in FluentNumberField

### ISSUE THREAD

**Issue by MvandeRuitenbeek** [microsoft/fast-blazor#185]
# 🐛 Bug Report

If iI provide a FluentNumberField in Blazor Wasm with a float or double value, only the integer part shows up. All numbers after the decimal separator are omitted. Also, min, max and step do not work as espected with fractional numbers. It doesn't matter if I bind it to a variable or not. Manually entering 1.2 or 1,2 does not work either. Tried both float and double values.

## 💻 Repro or Code Sample

`    <FluentNumberField @bind-Value="@test">Double</FluentNumberField>
`
where test;
`var test = 1.2`

## 🤔 Expected Behavior

FluentNumberField should display numbers such as 1.2 and 4.55 (tried both comma and dot, no difference).

## 😯 Current Behavior
It only displays the integer part of the number. Step, min and max do not work as espected either.

## 🌍 Your Environment

Blazor WASM project

* OS & Device:Windows on PC
* Browser Microsoft Edge, Google Chrome
* .NET 6.0 and FAST.Components.FluitUI 1.4.0

**Comment by vnbaaij** [comment]
Sorry, but I can't reproduce. This is what I get when running the WASM demo locally:
![image](https://user-images.githubusercontent.com/1761079/167824215-2c7d6d5f-2a22-40d5-a82d-869449a8098e.png)

With this code:
```
<p>
    <FluentNumberField @bind-Value="@exampleFloat">Float</FluentNumberField><br />
    Example float: @exampleFloat
    <br />
    Minimum value: @(float.MinValue); Maximum value: @(float.MaxValue)
</p>
<p>
    <FluentNumberField Step=0.25 @bind-Value="@exampleFloat">Float</FluentNumberField><br />
    Example float: @exampleFloat (step=0.25)
    <br />
    Minimum value: @(float.MinValue); Maximum value: @(float.MaxValue)
</p>
<p>
    <FluentNumberField @bind-Value="@exampleDouble">Double</FluentNumberField><br />
    Example double: @exampleDouble
    <br />
    Minimum value: @(double.MinValue); Maximum value: @(double.MaxValue)
</p>
<p>
    <FluentNumberField @bind-Value="@exampleDecimal">Decimal</FluentNumberField><br />
    Example decimal: @exampleDecimal
    <br />
    Minimum value: @(decimal.MinValue); Maximum value: @(decimal.MaxValue)
</p>

@code{
    int exampleInt { get; set; } = 123;
    long exampleLong { get; set; } = 999999999999;
    float exampleFloat { get; set; } = 123.45f;
    double exampleDouble { get; set; } = 456.32d;
    decimal exampleDecimal { get; set; } = Decimal.One / 3;
}

```
