### ISSUE TITLE
Icons missing popular brands and icon listing

### ISSUE THREAD

**Issue by ameyasubhedar** [microsoft/fast-blazor#186]
The icons seem to be missing the popular brands that are used often such as , 
- GitHub, Stripe, AWS, Microsoft, Azure etc...
- OS Icons Windows, Linus, macOS
- Technology icons
-etc...

Also please provide an icon preview page that will render all the available icons with a search capability.

**Comment by vnbaaij** [comment]
We are not planning to design or release our own icons. The icons you mention are not part of the Fluent UI System Icon collection (https://github.com/microsoft/fluentui-system-icons) that we are using. You can request new icons by creating issues in that repo. 

The demo site has an Icons page which has a search function. As there are over 11k icons, we are not showing them all on 1 page. The page can be found here: https://brave-cliff-0c0c93310.azurestaticapps.net/IconPage
