### ISSUE TITLE
Error when trying to add script in Blazor server side

### ISSUE THREAD

**Issue by chigivigi** [microsoft/fast-blazor#190]
# 🐛 Bug Report

When trying to add web components script in layout cshtml file I receive a error. The error message is: The name 'fluentui' does not exist in the current context.

## 💻 Repro or Code Sample

I copied the script file from the GitHub description in my _Layout.cshtml file and then the error is displayed.

## 🤔 Expected Behavior

The script should not show an error message and should not block the project from running.

## 😯 Current Behavior

The script shows a error message and the project cannot be run.

## 🌍 Your Environment

I am working in Visual Studio 2022 and running the project in Microsoft Edge Version 101.0.1210.47 (Official build) (64-bit).
The version of my visual studio 17.1.6.

**Comment by TheBigAvanger** [comment]
You need to "escape" the "@" sign, by using two "@" signs in a row.  This worked for me.

<script type="module" src="https://cdn.jsdelivr.net/npm/@@fluentui/web-components@2.0.2/dist/web-components.min.js"></script>
