### ISSUE TITLE
feat: Can we have shorter paths in the Microsoft.Fast.Components.FluentUI nuget package for usage with .NET MAUI?

### ISSUE THREAD

**Issue by s-beltz** [microsoft/fast-blazor#201]
# 🙋 Feature Request

Is it possible to flatten folder structure in the Microsoft.Fast.Components.FluentUI nuget package for usage with .NET MAUI?

We are developing a .NET MAUI application and would like to use the fast-blazor nuget package as documented in this repo. 

As this is a MAUI application Visual Studio produces sub folders for every target platform the app can be deployed to:

<img width="419" alt="image" src="https://user-images.githubusercontent.com/57802605/179250100-fc277a02-2680-4af7-add6-6694d75d08be.png">

We experience deployment errors in Visual Studio when starting our MAUI application:

`DEP1000: Cannot copy file "C:\Users\SaschaBeltz\.nuget\packages\microsoft.fast.components.fluentui\1.4.4\staticwebassets\icons\Accessibility\accessibility_16_filled.svg" to layout "C:\Temp\Test_Projects\LongPath_LongPath_LongPath_LongPath_2_Longer_Longer\MauiApp-FastBlazor\MauiApp-FastBlazor\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\wwwroot\_content\Microsoft.Fast.Components.FluentUI\icons\Accessibility\accessibility_16_filled.svg". DirectoryNotFoundException - Could not find a part of the path 'C:\Temp\Test_Projects\LongPath_LongPath_LongPath_LongPath_2_Longer_Longer\MauiApp-FastBlazor\MauiApp-FastBlazor\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\wwwroot\_content\Microsoft.Fast.Components.FluentUI\icons\Accessibility\accessibility_16_filled.svg'. [0x80070003]
`

We think that we are stuck here as 
* Visual Studio 2022 still seems to lack long path support.
* .NET MAUI itself needs to have a complex folder hierarchy to differentiate target platforms.
* We are not able to move our own code base to shorter paths.

Do you see any chance on reducing path lengths in your nuget package? 

## 💻 Examples

Just place the attached solution (VS Preview 2022 required) in a deeply nested directory and start the application on Windows.
[MauiApp-FastBlazor.zip](https://github.com/microsoft/fast-blazor/files/9122044/MauiApp-FastBlazor.zip)

**Comment by vnbaaij** [comment]
Hi,
Sorry but t here is nothing we can do here. The `_content\Microsoft.Fast.Components.FluentUI\icons\Accessibility\accessibility_16_filled.svg` is there because of Blazor convention and the need to have a structure in the 11k+ set of icons.
The `LongPath_LongPath_LongPath_LongPath_2_Longer_Longer` seems to me where you have gains to make. That is totally under your control

**Comment by s-beltz** [comment]
Hi @vnbaaij, thank you for pointing out the amount of assets you put into your package. I now understand the need for additional folders.

One more thing before closing this request: the path you mentioned was just for repro purposes. 
Our VS solution is also quite complex with the need for additional folders containing directory.build.props.
Additionally .NET MAUI needs folders for every target platform. All this adds up to a long path. 
Hopefully there will be long path support in VS some time in the future. :slightly_smiling_face:

**Comment by Ogglas** [comment]
@vnbaaij Got the error below when publishing a Blazor application with Fluent UI Web Components. This means that any custom path above ~56 characters will fail. I tried to Enable Long Paths and reboot my computer but it did not help.

https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry

I agree with @s-beltz and hope Visual Studio will implement long paths soon:

https://developercommunity.visualstudio.com/t/allow-building-running-and-debugging-a-net-applica/351628

> C:\Program
> Files\dotnet\sdk\6.0.402\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(615,5):
> Warning MSB3026: Could not copy
> "C:\Users\oscar\\.nuget\packages\microsoft.fast.components.fluentui\1.5.3\staticwebassets\icons\TextDirectionRotate270Right\en\text_direction_rotate_270_right_24_regular.svg"
> to
> "C:\Users\oscar\source\repos\MyVeryLongProjectName12345678\MyVeryLongProjectName12345678\Server\obj\Release\net6.0\PubTmp\Out\wwwroot\_content\Microsoft.Fast.Components.FluentUI\icons\TextDirectionRotate270Right\en\text_direction_rotate_270_right_24_regular.svg".
> Beginning retry 10 in 1000ms. Could not find a part of the path
> 'C:\Users\oscar\source\repos\MyVeryLongProjectName12345678\MyVeryLongProjectName12345678\Server\obj\Release\net6.0\PubTmp\Out\wwwroot\_content\Microsoft.Fast.Components.FluentUI\icons\TextDirectionRotate270Right\en\text_direction_rotate_270_right_24_regular.svg'.
> C:\Program
> Files\dotnet\sdk\6.0.402\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(615,5):
> Warning MSB3026: Could not copy
> "C:\Users\oscar\.nuget\packages\microsoft.fast.components.fluentui\1.5.3\staticwebassets\icons\TextDirectionRotate270Right\en\text_direction_rotate_270_right_20_regular.svg"
> to
> "C:\Users\oscar\source\repos\MyVeryLongProjectName12345678\MyVeryLongProjectName12345678\Server\obj\Release\net6.0\PubTmp\Out\wwwroot\_content\Microsoft.Fast.Components.FluentUI\icons\TextDirectionRotate270Right\en\text_direction_rotate_270_right_20_regular.svg".
> Beginning retry 10 in 1000ms. Could not find a part of the path
> 'C:\Users\oscar\source\repos\MyVeryLongProjectName12345678\MyVeryLongProjectName12345678\Server\obj\Release\net6.0\PubTmp\Out\wwwroot\_content\Microsoft.Fast.Components.FluentUI\icons\TextDirectionRotate270Right\en\text_direction_rotate_270_right_20_regular.svg'.
> C:\Program
> Files\dotnet\sdk\6.0.402\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(615,5):
> Error MSB3027: Could not copy
> "C:\Users\oscar\.nuget\packages\microsoft.fast.components.fluentui\1.5.3\staticwebassets\icons\TextDirectionHorizontalRight\ko\text_direction_horizontal_right_24_regular.svg"
> to
> "C:\Users\oscar\source\repos\MyVeryLongProjectName12345678\MyVeryLongProjectName12345678\Server\obj\Release\net6.0\PubTmp\Out\wwwroot\_content\Microsoft.Fast.Components.FluentUI\icons\TextDirectionHorizontalRight\ko\text_direction_horizontal_right_24_regular.svg".
> Exceeded retry count of 10. Failed.
