### ISSUE TITLE
fix: Clearing the input in FluentSearch Component doesn't trigger onInput

### ISSUE THREAD

**Issue by EddyHaigh** [microsoft/fast-blazor#203]
# 🐛 Bug Report

## 💻 Repro or Code Sample

``` csharp

        <FluentSearch @oninput="HandleSearch" Placeholder="e.g. Italy">Search location or country</FluentSearch>
        <FluentDataGrid RowsData="GridData" ColumnDefinitions="ColumnDefinitions" />

@code
{
    // Imagine a list of countries assigned to this
    private IList<string> _countries = new List<string>() { "United Kingdom", "Italy", "Germany" };
 
    public List<ColumnDefinition<string>> ColumnDefinitions { get; } = new()
    {
        new ColumnDefinition<string>("Country Name", c => c)
    };

    public IList<string> GridData { get; set; }

    private void HandleSearch(ChangeEventArgs args)
    {
        var filter = args?.Value as string;
        if (string.IsNullOrWhiteSpace(filter))
        {
            GridData = _countries.ToList();
        }
        else
        {
            GridData = _countries
                .Where(c => c.Contains(filter, StringComparison.CurrentCultureIgnoreCase))
                .ToList();
        }
    }
}
```

## 🤔 Expected Behavior

When using the clear icon on the fluent search, the OnInput event should trigger as if someone cleared the result manually.

## 😯 Current Behavior

Clearing the input does not trigger the OnInput event so the filter does not get reset.

## 🔦 Context

Trying to filter the clear search for items in a datagrid or even listbox etc.

## 🌍 Your Environment

* OS & Device: Windows 10
* Browser Microsoft Edge & Chrome
* .NET and FAST Version Dotnet 6, Microsoft.Fast.Components.FluentUI 1.5.0, FluentUI WebComponents 2.5.3

**Comment by vnbaaij** [comment]
A fix for this has been rolled out in the web components script. Only thing is it fires an `onchange` and not an `oninput`.
An example can be found in `examples\FluentUI.Demo.Shared\Pages\Search\Examples\SearchInteractive.razor`
