### ISSUE TITLE
FluentRadio Check Checked state

### ISSUE THREAD

**Issue by kaldaf** [microsoft/fast-blazor#204]
# 🐛 Bug Report

Hey I want to check if FluentRadio is checked. 

## 💻 Repro or Code Sample

Whole code:

```c#
@page "/settings"
@using System.IO.Ports;
@using Microsoft.Fast.Components.FluentUI

<h1>Settings</h1>
<p>Selected port <em>@(selectedPort != null ? selectedPort : "none")</em></p>
@if (ports != null)
{
    <FluentRadioGroup>
        @foreach (string p in ports)
        {
            // TO DO FIX THIS!
            <FluentRadio @Checked="@(p == selectedPort)" @onclick="@(e => SetPort(p))">@p</FluentRadio>
            // OR ?
            <FluentRadio Checked="@(p == selectedPort)" @onclick="@(e => SetPort(p))">@p</FluentRadio>
        }
    </FluentRadioGroup>
}

@code {
    string selectedPort = null;
    List<string> ports = new List<string>();
    string[] pList = SerialPort.GetPortNames();

    protected override void OnInitialized()
    {
        foreach (string p in pList)
        {
            ports.Add(p);
        }
        selectedPort = Preferences.Get("port", null);
    }

    private void SetPort(string portName)
    {
        Preferences.Set("port", portName);
        selectedPort = portName;
    }
}

```

## 🤔 Expected Behavior

When the page loads i will have a radio button

## 😯 Current Behavior

With ```@Checked="@(selectedPort == port)"``` still error.

## 💁 Possible Solution

Would be fine create docs based on Blazor, not React, with examples and API like Angular Material:
[Example](https://material.angular.io/components/radio/api)

## 🔦 Context
-
## 🌍 Your Environment

Windows 10, .NET MAUI Blazor (Windows Machine App), .NET 6, Fast latest version, Microsoft Edge version 103.0.1264.62

**Comment by IvanFeric** [comment]
Try replacing `foreach (string p in ports)` with `foreach (string port in ports)`. Basically, `foreach` is using variable named `p` for iterating over `ports` but you're using variable named `port` (probably component level field if it's compiling) inside the block..

**Comment by kaldaf** [comment]
Sorry, I rewrote that here on github, otherwise I'm using the p string in the ports there. But I'm still stuck in checked state.
![image](https://user-images.githubusercontent.com/50804954/179846734-505e04f1-c59a-45bf-9f55-1789b703b266.png)

**Comment by kaldaf** [comment]
Hi, I missed the examples folder so I put it together somehow

```C#
<FluentRadioGroup ValueChanged="@(e => SetPort(e))" Value="@selectedPort">
        @foreach (string p in ports)
        {
            <FluentRadio Value="@p" Checked="@(p == selectedPort)">@p</FluentRadio>
        }
    </FluentRadioGroup> 
```
