### ISSUE TITLE
Fluent Dialog cannot change size

### ISSUE THREAD

**Issue by chigivigi** [microsoft/fast-blazor#207]
# 🐛 Bug Report

I cannot change the default height and width of the fluent dialog component.
Style property for height and width is ignored.

## 💻 Repro or Code Sample

`
<FluentDialog Hidden="ModalHidden" @ref="confirmDialog"  Modal="false" style="width:30em;height:15em">
        <h2 style="margin-top:3em">xx</h2>
        <p>Do you want to continue ?</p>
        <FluentButton style="width:6em;margin-right:2em" @onclick="@yes">YES</FluentButton>
        <FluentButton style="width:6em" @onclick="@no">NO</FluentButton>
</FluentDialog>
`

## 🤔 Expected Behavior

It should change the dialog size.

## 😯 Current Behavior

It does not change dialog size, slot remains the same size.(640x480)px

## 💁 Possible Solution

-

## 🔦 Context

It affects the user experience. Dialog is very big but the content is small and fills only 20% of dialog.

## 🌍 Your Environment

Blazor server hosted app, Microsoft Edge.

**Comment by sagemodeninja** [comment]
It would also be convenient to have dedicated Width/Height parameters.

**Comment by vnbaaij** [comment]
You nee to use the CSS variables `--dialog-width` and `--dialog-height` for this, i.e. put something like this in your CSS:
```
::part(control) {
    --dialog-width: 300px;
    --dialog-height: 350px;
}
```

We'll look at adding dedicated Width/Height parameters at a later date.

**Comment by chigivigi** [comment]
@vnbaaij thank you for your help, after adding the css example in my global css file the fluent dialog had changed its size.

**Comment by LuohuaRain** [comment]
It would be better if Fast Blazor adding Width/Height parameters

**Comment by Hsiaye** [comment]
If the `::deep` needs to take effect, `<FluentDialog>` needs to be written into the `div`.

**Comment by vnbaaij** [comment]
That is correct, yes. As is always the case when using ::deep
