### ISSUE TITLE
fix: MinLength/MaxLength of FluentSearch doesn't work when put in FluentToolBar

### ISSUE THREAD

**Issue by dawnchan030920** [microsoft/fast-blazor#208]
# 🐛 Bug Report

MinLength/MaxLength of FluentSearch doesn't work when put in FluentToolBar.

## 💻 Repro or Code Sample

```html
<FluentToolBar>
    <FluentSearch MinLength="...">
    </FluentSearch>
</FluentToolBar>
```

## 🤔 Expected Behavior

When the width allocated for `FluentSearch` is smaller than its current width, it should scale itself to fit until it's even smaller than its `MinLength`.

## 😯 Current Behavior

The FluentSearch is put to the second row, which means the mechanism of `FluentToolBar` is prior to the `FluentSearch`'s.

## 🔦 Context

I'm trying to put the `FluentSearch` in a `FluentToolBar` and hope that FluentSearch can scale itself.

## 🌍 Your Environment

* OS & Device: Windows
* Browser: Microsoft Edge
* .NET: 6.0.400
* Microsoft.Fast.Components.FluentUI: 1.5.0

**Comment by vnbaaij** [comment]
Are you assuming `MinLength`/`MaxLentgh` influence the width of the `FluentSearch`? Because that is not the case. those parameters are only influencingthe number of characters you can input. For changing the width, you should use normal CSS ways of doing that.

**Comment by vnbaaij** [comment]
No interaction...
