### ISSUE TITLE
fix: error when submitting an EditorForm that has FluentNumberField with decimal value.

### ISSUE THREAD

**Issue by sagemodeninja** [microsoft/fast-blazor#209]
# 🐛 Bug Report

An error occurs when submitting an EditorForm via a submit button when it has a FluentNumberField whose
value has a decimal place e.g. `1.2`.

## 💻 Repro or Code Sample

Repository of basic reproduction code: https://github.com/sagemodeninja/fluent-number-field-bug-repro

Markup:
```html
<EditForm Model=@_model>
    <FluentNumberField @bind-Value=@_model.Amount />
    <button type="submit">Sumbit</button>
</EditForm>
```

Steps:
1. Enter a whole number.
2. Click submit, check the console to confirm that it says `Form was valid.`
3. Enter a value with decimal place e.g. `1.2`.
4. Click submit again, and confirm that the console says `An invalid form control with name='' is not focusable.`

## 🤔 Expected Behavior

Form should submit without errors.

## 😯 Current Behavior

After clicking the submit button, an error will occur with the ff. message:
`An invalid form control with name='' is not focusable.`

## 🔦 Context

I was trying to use the component to input monetary value.

## 🌍 Your Environment

* OS & Device: macOS Monterey 12.5, MacBook Pro 14 M1
* Browser: Safari 15.6
* .NET and FAST Version: .NET 6.0, Microsoft.Fast.Components.FluentUI 1.5.0, `latest` script.

**Comment by vnbaaij** [comment]
For now, this can be fixed with actually supplying a name attribute to the `FluentNumberField`c like this:

```<FluentNumberField @bind-Value=@_model.Amount name="c1" />```

You should get this:
<img width="364" alt="image" src="https://user-images.githubusercontent.com/1761079/184864834-0b853c31-5b80-42b5-aa28-433e0ca2d92c.png">

I'll look for a more permanent solution(auto0generatingname or something like that)

**Comment by sagemodeninja** [comment]
Hi @vnbaaij.

Can you check your console when clicking submit.
Mine will give this error: `An invalid form control with name='c1' is not focusable.`

Giving the control a name or making it focusable with `tabindex=0` doesn't fix it for me.

**Comment by vnbaaij** [comment]
Yes, I still see the error as well then (but only when actually using decimal values, there is no problem when using 'whole' numbers). After trying all the solutions from Binging the problem, the only way I can make the error go away is to add a `novalidate` to the `<form>` tag. 
It seems to be an underlying Chrome/Edge render engine issue that I can't fix from the Blazor side...Closing it as not fixable for now

**Comment by LuohuaRain** [comment]
One of the issues I encountered while working with FluentNumberField is that it does not integrate well with EditForm. A possible solution is to use <InputNumber> instead, <InputNumber> works fine with EditForm and decimal value.

I tried to use <FluentNumberField > with Step = "any" within EditForm(form), but I still got a warning message saying "please enter a valid value. the two nearest valid values are 0 and 1". This seems to be a bug that needs to be fixed.
