### ISSUE TITLE
fix: OnExpandedChange and OnSelectedChange in FluentTreeView

### ISSUE THREAD

**Issue by FedericoSMEC** [microsoft/fast-blazor#210]
# 🐛 Bug Report

Expanding the FluentTreeView does not trigger the OnExpandedChange event. Similarly, selecting a node does not update the currentSelected property, nor does it trigger the OnSelectedChange event. 

I am currently testing with the sample from this repository.

## 💻 Repro or Code Sample

    <FluentTreeView class="border file-tree" @bind-CurrentSelected="currentSelected" 
        OnExpandedChange="HandleOnExpandedChanged">
        <FluentTreeItem Text="Root item 1">
            <FluentTreeItem Text="Flowers">
                <FluentTreeItem Disabled="true" Text="Daisy" />
                <FluentTreeItem Text="Sunflower" />
                <FluentTreeItem Text="Rose" />
            </FluentTreeItem>
            <FluentTreeItem Text="Nested item 2" />
            <FluentTreeItem Text="Nested item 3" />
        </FluentTreeItem>
    </FluentTreeView>

    <p>Current selected tree item is @currentSelected.Text</p>
    <p>Current expanded/collapsed tree item is @currentAffected.Text</p>

    @code {

        FluentTreeItem currentSelected = new();
        FluentTreeItem currentAffected = new();

        private void HandleOnExpandedChanged(FluentTreeItem item)
        {
            currentAffected = item;
        }
    }

## 🤔 Expected Behavior

FluentTreeView should fire those events, in order to be able to detect which node has been selected/expanded.

## 😯 Current Behavior

The events are not triggered.

## 🔦 Context

I am using this tree view to display a file system view (note my environment below). I'd need to know which node is expanded so I can load its sub-directories

## 🌍 Your Environment

* OS & Device: Windows 10
* Browser:  **I am using Blazor with .NET MAUI to develop a desktop application**
* .NET and FAST Version:  .NET 6.0.8 - Fast.Components.FluentUI 1.5.1

**Comment by vnbaaij** [comment]
You are probably getting errors because the web components script is not being loaded. I'm guessing it is the same error as you have reported in #211. 
If you are able to get the demo page loaded properly (maybe on your phone) and without errors, you should see the events being raised as advertised.

**Comment by FedericoSMEC** [comment]
@vnbaaij  Thank you for your reply. The web components seem to be loaded fine, I can see the successful http request to load the web-components.min.js . I also tried to copy all the contents of the file into a local file and import that into my index.html but I have the same result.

Could this be related to me using .NET MAUI for a windows desktop app rather than a web application?

![image](https://user-images.githubusercontent.com/103231088/186282806-e2d4f5f8-7c2d-476d-9530-a4bad1f182af.png)

**Comment by vnbaaij** [comment]
Is it using Blazor Hybrid or just using WebView with Blazor WASM app?

**Comment by FedericoSMEC** [comment]
I believe it's Blazor Hybrid. I created a new project following the instructions in [Build a .NET MAUI Blazor app](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/maui?view=aspnetcore-6.0) .
