### ISSUE TITLE
fix: FluentUI Demo for Blazor is not launching

### ISSUE THREAD

**Issue by FedericoSMEC** [microsoft/fast-blazor#211]
# 🐛 Bug Report

When visiting the demo website, as indicated by Microsoft's website, the page gets stuck with only a "Loading..." text and CORS errors appear in the console.

![image](https://user-images.githubusercontent.com/103231088/186068550-a60b0b0d-9a6b-41ec-b549-87ae5e9c1fd9.png)

## 💻 Repro or Code Sample

Click [here](https://brave-cliff-0c0c93310.azurestaticapps.net/TreeViewPage?_sm_au_=iVVfHFtjjHNjrqSqQ3QqjKst8fk1c)

## 🌍 Your Environment

* OS & Device: Windows 10
* Browser: Microsoft Edge

**Comment by vnbaaij** [comment]
Hi,

There is something in the way on your end. You seem to be stuck somewhere on gateway.zscloud.net. 
If I use your 'Click here' link above, I'm getting the site as expected: 
<img width="460" alt="image" src="https://user-images.githubusercontent.com/1761079/186111673-61714ef1-f7bc-46a8-96d0-116520c42f97.png">

**Comment by FedericoSMEC** [comment]
Thank you, I'll have a deeper investigation on my end.
