### ISSUE TITLE
fix: 2-Way-Binding does not work in FluentListbox

### ISSUE THREAD

**Issue by ascendise** [microsoft/fast-blazor#213]
# 🐛 Bug Report

When binding a value to a FluentListbox, the bound value does not change when selecting an item in the list.

## 💻 Repro or Code Sample

```HTML+Razor
<FluentListbox @bind-Value=_value>
    <FluentOption Value=@("First Value")>First Value</FluentOption>
    <FluentOption Value=@("Second Value")>Second Value</FluentOption>
    <FluentOption Value=@("Third Value")>Third Value</FluentOption>
</FluentListbox>
<h1>@_value</h1>

@code {
    private string _value = string.Empty;
}
```
## 🤔 Expected Behavior
The bound property should change to the selected value. 
E.g. when selecting the option _"Second Value"_, `_value` should be set to _"Second value"_

## 😯 Current Behavior

The bound property does not change when selecting an option in the FluentListbox. The binding does work in one way, so changing the bound variable changes the selection in the FluentListbox. 
E.g. when I change `_value` to _"Second Value"_, the selected option in the FluentListbox changes to the option _"Second Value"_.

## 💁 Possible Solution
The `@onchange`-Event of the FluentListbox does not get fired when selecting an option in the Fluentlistbox. So the issue could lie somewhere there.

## 🔦 Context
I am trying to list different _environments_ a user could choose from and then change to that _environment_. A FluentSelect would do the job as well but the FluentListbox just looks better in the context it is used.

## 🌍 Your Environment
* OS & Device: Windows 10 on PC
* Browser: Mozilla Firefox 103.0.2
* .NET and FAST Version: .NET 6 and Microsoft.Fast.Components.FluentUI 1.5.1

**Comment by enetstudio** [comment]
I've answered your question in Stackoverflow... ([See if it works for you...](https://stackoverflow.com/a/73506684/6152891))

**Comment by Ogglas** [comment]
@vnbaaij Should this really be closed?

Both Microsoft Learn and Fast Blazor Example shows an example with `@bind-Value` and it is always `null` after select. This does not seem right?

Documentation also says: 

> The <FluentListbox> supports data binding, but does not hook in any events.

Using NuGet Microsoft.Fast.Components.FluentUI 1.5.3 with fluentui/web-components 2.5.6.

Example:

<FluentListbox @bind-Value=@listboxValue>
    <FluentOption Value="@("AL")">Alabama</FluentOption>
    <FluentOption Value="@("AK")">Alaska</FluentOption>
    <FluentOption Value="@("AZ")">Arizona</FluentOption>
    <FluentOption Value="@("AR")">Arkansas</FluentOption>
</FluentListbox>

@code {
    string? listboxValue;
}

https://learn.microsoft.com/en-us/fluent-ui/web-components/components/listbox?pivots=blazor

https://brave-cliff-0c0c93310.azurestaticapps.net/Listbox

**Comment by vnbaaij** [comment]
The underlying fluent-listbox does not fire a change event, so that is the source of the problem.
However, for version 2 I'm working on a solution where an event gets raised through the option. Hold on a bit longer. A beta will be out in the next week.

**Comment by wegylexy** [comment]
Also, setting `_value` to `null` or navigating back and forth won't update the selected options. I am invoking JavaScript to work around.
```js
function selectFluentOption(listbox, value) {
    listbox.selectedOptions = [...listbox.querySelectorAll("fluent-option")].filter(o => o.value === value);
}
```
```razor
<FluentListbox TOption=string @ref=listbox Value=@Value ValueChanged=@(value => Value = value)>
    <FluentOption Value=@("First Value")>First Value</FluentOption>
    <FluentOption Value=@("Second Value")>Second Value</FluentOption>
    <FluentOption Value=@("Third Value")>Third Value</FluentOption>
</FluentListbox>
<h1>@Value</h1>

@code {
    [Parameter]
    public string Value { get; set; }
    private FluentListbox<string>? listbox;
    protected override Task OnAfterRenderAsync(bool firstRender) => listbox is { Element: { } element } ?
        JSRuntime.InvokeVoidAsync("selectFluentOption", element, _value).AsTask() :
        Task.CompletedTask;
}
```
The interop is called 3 times on a single selection change though.
