### ISSUE TITLE
WASM AOT precompiling fails for Microsoft.Fast.Components.FluentUI.dll

### ISSUE THREAD

**Issue by MertUssakliMSFT** [microsoft/fast-blazor#214]
# 🐛 Bug Report

We compile our Blazor WASM app with AOT compilation in order to improve client-side performance. When we took a dependency on FluentUI, our regular builds worked as normal but the `dotnet publish` step that was set to run AOT compilation failed. 

```
<RunAOTCompilation>true</RunAOTCompilation>
<RunAOTCompilationAfterBuild>true</RunAOTCompilationAfterBuild>
<WasmNativeStrip>false</WasmNativeStrip>
```

I could not find any mentions of this issue anywhere, including on this GitHub page. 

## 💻 Repro or Code Sample

Create any Blazor WASM app, add the build configurations above to the `csproj`, take a dependency on Microsoft.Fast.Components.FluentUI, build.

## 🤔 Expected Behavior

Successful build!

## 😯 Current Behavior

Error as follows:
```
11>[Microsoft.Fast.Components.FluentUI.dll] Exec (with response file contents expanded) in C:\Users\meussakl\Code\Office-Performance-TraceViewer\TraceViewerWasm\Client\obj\Release\net6.0\wasm\for-build\aot-in: MONO_PATH=C:\Users\meussakl\Code\Office-Performance-TraceViewer\TraceViewerWasm\Client\obj\Release\net6.0\wasm\for-build\aot-in;C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.8\runtimes\browser-wasm\native\;C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.8\runtimes\browser-wasm\\lib\net6.0 MONO_ENV_OPTIONS= C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.browser-wasm\6.0.8\Sdk\..\tools\mono-aot-cross.exe --debug --llvm "--aot=no-opt,static,direct-icalls,deterministic,dwarfdebug,llvm-path=C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.4\tools\bin\,static,llvmonly,interp,asmonly,llvm-outfile=C:\Users\meussakl\Code\Office-Performance-TraceViewer\TraceViewerWasm\Client\obj\Release\net6.0\wasm\for-build\Microsoft.Fast.Components.FluentUI.dll.bc.tmp" "Microsoft.Fast.Components.FluentUI.dll"
11>C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.8\Sdk\WasmApp.Native.targets(511,5): error : Precompiling failed for C:\Users\meussakl\Code\Office-Performance-TraceViewer\TraceViewerWasm\Client\obj\Release\net6.0\wasm\for-build\aot-in\Microsoft.Fast.Components.FluentUI.dll.
11>C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.8\Sdk\WasmApp.Native.targets(511,5): error :
```

## 🌍 Your Environment

Windows build on VS2022, project running on .NET 6. Failure repos in Azure DevOps build lab as well as locally. FAST version is 1.5.1 (latest public version)

**Comment by MertUssakliMSFT** [comment]
Possibly related: https://github.com/dotnet/runtime/issues/61352

**Comment by vnbaaij** [comment]
I've confirmed AOT precompiling DOES NOT work on the current .NET 6 version (although the issue mentioned above suggests that the fix has been backported from .NET 7 to .NET 6).
I've confirmed AOT precompiling DOES work on thecurrent .NET 7 (preview 7) version. This was done through testing `dotnet publish` from the `net7` branch
As the first RC for .NET 7 (with go-live support) is just around the corner (~2 weeks from now), I won't be investing more time on getting it sorted on .NET 6 unless I hear a fix has indeed been backported

**Comment by baywet** [comment]
I've upgraded my project to net7, and with 7.0.0-rc.2.22472.3 I'm getting the following error

```
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.0-rc.2.22472.3\Sdk\WasmApp.Native.targets(583,5): error : Precompiling failed for <...>\obj\release\net7.0\linked\Microsoft.Fast.Components.FluentUI.dll with exit code -1073741571.
```

It seems that a regression came up @vnbaaij
