### ISSUE TITLE
FluentIcon cache control

### ISSUE THREAD

**Issue by ehsangfl** [microsoft/fast-blazor#235]
FluentIcon sends a request on every render of Icon.

if we have page with 100 Items and every item has two same icons (for example edit and delete icon), FluentIcon send 200 request to server for load svg icon instead of 2 request.

or in some scenarios, we can use an element that is hide and show it by mouse over or something else and FluentIcon loads svg on every show/hide state. 

I think we need a cache logic to decrease unneeded request 

we can do it on webclient and use internal caching of messagehandler
another solution is to use  a static dictionary and save requests results on it

**Comment by vnbaaij** [comment]
This is taken care of in V2. You can see how it works at https://brave-cliff-0c0c93310-233.centralus.azurestaticapps.net/

I'm leveraging the standard Cache Web API (https://developer.mozilla.org/en-US/docs/Web/API/Cache) for this which is supported on all modern browsers so not expecting any issues. I added a default (non-configurable) expiration period of 7 days.

Example of what it looks like in the Developer Tools:
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/1761079/197385806-e9f50397-fdbc-48fd-a3a0-3f61c66f74c7.png">

**Comment by vnbaaij** [comment]
This is closed with V2 (RC1 is out now)
