### ISSUE TITLE
Can't show FluentDialog unless initially shown

### ISSUE THREAD

**Issue by chucker** [microsoft/fast-blazor#238]
# 🐛 Bug Report

I cannot seem to add a `FluentDialog` that is _not_ initially visible but _can_ be shown later on.

## 💻 Repro or Code Sample

```cshtml
<FluentDialog @ref="MyDialog" Hidden="true">
    <h2>Dialog referenced from object</h2>
</FluentDialog>

<Menu>
    <FluentMenu>
        <FluentMenuItem @onclick=ShowDialog>Show dialog…</FluentMenuItem>
    </FluentMenu>
</Menu>

@code {
    FluentDialog MyDialog;

    private void ShowDialog()
    {
        MyDialog.Show();
    }

    private void HideDialog()
    {
        MyDialog.Hide();
    }
}
```

## 🤔 Expected Behavior

* The dialog should not initially show
* When clicking the menu item, it should show

## 😯 Current Behavior

* The dialog does not initially show
* However, when clicking the menu item, it doesn't show either

If I remove `Hidden="true"`, the menu item does work, but (obviously), the dialog also immediately shows.

## 🔦 Context

I need a dialog that shows up once I click a menu item. It should not show up any sooner than that.

## 🌍 Your Environment

* OS & Device: macOS 12.6 on MacBook Pro (14-inch, 2021) (ARM64)
* Browser: Apple Safari Version 16.0 (17614.1.25.9.10, 17614)
* .NET: 6.0.10
* FAST: 1.5.3

**Comment by chucker** [comment]
OK, if I instead bind the `Hidden` property myself, it works:

```cshtml
<FluentDialog @ref="MyDialog" Hidden="@MyDialogIsHidden">
    <h2>Dialog referenced from object</h2>
    <button @onclick=HideDialog>Close Me</button>
</FluentDialog>

<FluentMenu>
    <FluentMenuItem @onclick=ShowDialog>Show dialog…</FluentMenuItem>
</FluentMenu>

@code {
    FluentDialog MyDialog;
    bool MyDialogIsHidden = true;

    private void ShowDialog()
    {
        MyDialogIsHidden = false;
    }

    private void HideDialog()
    {
        MyDialogIsHidden = true;
    }
}
```

But I don't think the `Show()`/`Hide()` methods quite work as intended.

**Comment by vnbaaij** [comment]
This is fixed in V2 (R1 is out now)
