### ISSUE TITLE
fix: blazor wasm AOT in net7 rc2

### ISSUE THREAD

**Issue by baywet** [microsoft/fast-blazor#240]
# 🐛 Bug Report

Opening a new issue to provide visibility to this since I didn't get a reply to #214 but it's essentially the same thing.

## 💻 Repro or Code Sample

```xml
<RunAOTCompilation>true</RunAOTCompilation>
<RunAOTCompilationAfterBuild>true</RunAOTCompilationAfterBuild>
<WasmNativeStrip>false</WasmNativeStrip>
```

project targeting net7

```shell
dotnet publish -c Release
```

## 🤔 Expected Behavior

AOT and assembly trimming to function properly.

## 😯 Current Behavior

getting the following error message

```
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.0-rc.2.22472.3\Sdk\WasmApp.Native.targets(583,5): error : Precompiling failed for <...>\obj\release\net7.0\linked\Microsoft.Fast.Components.FluentUI.dll with exit code -1073741571.
```

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC] windows 11 x64
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox] N/A
* .NET and FAST Version [e.g. 1.8.0] 7.0.0-rc.2.22472.3, 1.6.0-rc.2
CC @MertUssakliMSFT

**Comment by MertUssakliMSFT** [comment]
Thanks for opening this bug. I've confirmed that AOT also breaks on our project with this package. A fix to this would be appreciated before official .NET 7 release.

**Comment by vnbaaij** [comment]
I was able to track down where the publish process broke. It was on the (mostly generated) `FluentIcons` class. Made some changes there (see [#0f0fd8e7](https://github.com/microsoft/fast-blazor/commit/0f0fd8e7fd0b89c2284e3a7ed3b6e12a098aaa63)) and after that was able to use `dotnet publish -c Release -o publish` with both `-f net6.0` as `-f net7.0` on the `FluentUI.Demo.Client` project with the added settings mentioned above.

Note: I installed the .NET 6 wasm tools workload (`dotnet workload install wasm-tools-net6`) and I am running an (internal to MS) Visual Studio preview which might have a newer version of the .NET 7 wasm tools that are generally available.

**Comment by baywet** [comment]
Thanks for the quick turn around. When are you planning to release that patch to nuget?

**Comment by vnbaaij** [comment]
The plan was to get it out in the final 1.6 release (together with the .NET 7 release). But I can also do a 1.6.0-rc.3 release after @MertUssakliMSFT has done some tests.

**Comment by MertUssakliMSFT** [comment]
Sorry about the delay, I can confirm that the fix works.
