### ISSUE TITLE
fix: [Incorrect behavior of keyboard arrows] in [fluent-data-grid with editable controls]

### ISSUE THREAD

**Issue by TPIvan** [microsoft/fast-blazor#241]
# 🐛 Bug Report

## 💻 Repro or Code Sample
I have attempted to use the grid with editable controls from the sample page [Data grid](https://brave-cliff-0c0c93310.azurestaticapps.net/DataGrid)  in section "With RowItemTemplate".
The problem is that when I place the cursor to a grid textbox and press keyboard arrow the cursor doesn't move to the next next letter but to next cell. When the grid is created in CodePen without Blazor the behavior is correct. 

## 🤔 Expected Behavior
expected behavior (from version without blazor https://codepen.io/TPIvan/pen/XWYKawj) 
1. cursor placed in a cell (by mouse click)
![grid cursor 1](https://user-images.githubusercontent.com/39948593/199944478-2e1d9562-9bb2-470e-9773-f49cd6ae0326.png)

2. after pressing the right arrow the cursor goes to the second character 
![grid cursor 2](https://user-images.githubusercontent.com/39948593/199944835-e380634e-11b8-4ff3-a423-729189f1a5eb.png)

## 😯 Current Behavior
from  page [Data grid](https://brave-cliff-0c0c93310.azurestaticapps.net/DataGrid)  in section "With RowItemTemplate"
The first image would be the same as in Expected Behavior so I am not repeating it.
2. After pressing the right arrow 
![grid cursor 3](https://user-images.githubusercontent.com/39948593/199946422-b42c6726-cc33-49c1-a262-7ccadb06cb2a.png)

## 🌍 Your Environment
The screenshots are from Vivaldi browser, but behavior is the same with Chrome. I have observed the same behavior in grid created in VS 2022 with nuget 1.6.0-rc.2 (widows 10, last library version https://cdn.jsdelivr.net/npm/@@fluentui/web-components/dist/web-components.min.js) and also in compiled sample from a clone version of the fast-blazor repository.

**Comment by vnbaaij** [comment]
This seems to be a bug in the web components script. If you change the JS in your codepen to use the latest version:
`import { fluentDataGrid, provideFluentDesignSystem } from "https://unpkg.com/@fluentui/web-components@2.5.8";`
you'll observe that the error happens there too

**Comment by TPIvan** [comment]
Thanks form answer. I have confirmed your conclusion other way round. I have put version 2.0.0 to my testing application and it works correctly. Can you recommend which version of FAST framework I should use?

**Comment by vnbaaij** [comment]
It depends...😁 Generally speaking I would say the latest. For example, I know in the latest version some code was added with which you can detect changing accordion items. If this grid/keyboard thing is important to you, you can use the 2.0.0 version (or try later versions until it breaks). Just be aware that other things might break because they were fixed in later versions.
