### ISSUE TITLE
back RowData property to DataGridRow

### ISSUE THREAD

**Issue by ehsangfl** [microsoft/fast-blazor#242]
why RowData property removed from DataGridRow in V2?
it is usefull for selected item or clicked item.

**Comment by vnbaaij** [comment]
V2 is using a completely new grid implementation based on QuickGrid (https://github.com/aspnet/AspLabs/tree/main/src/QuickGrid). 
Take a look at the Template columns sample at https://brave-cliff-0c0c93310-233.centralus.azurestaticapps.net/DataGrid to see how you can interact with cells/rows
