### ISSUE TITLE
feat: add ability to use other type of collection to/in FluentDataGrid

### ISSUE THREAD

**Issue by TPIvan** [microsoft/fast-blazor#244]
# 🙋 Feature Request

## 🤔 Expected Behavior
When I have any type of generic collection I want to be able to show it in the grid. 

## 😯 Current Behavior
It is possible to use only `List<TItem>`.
When a different type collection is used there is a compilation error. For example:

`Error (active)	CS1503	Argument 5: cannot convert from 'System.Collections.Generic.ICollection<MyItem>' to 'System.Collections.Generic.List<MyItem>'`	

## 💁 Possible Solution
Changing type of property

     public List<TItem>? RowsData { get; set; }
from `List<TItem>` to `IEnumerable<TItem>` would solve the problem.

## 🔦 Context
I would like to be able show an Entity Framework property corresponding to a 1-to-many relationship which has type `ICollection<TItem>` as a source of a grid.

Currently it is necessary to create extra list containing related data, which is at least not convenient.
I think that generic list as a grid data source is too restrictive. From a quick check of source code I conclude that the change will not create any problem.

**Comment by vnbaaij** [comment]
This is fixed in V2 where we will have integrated the QuickGrid component. `RowsData` is of type `IQueryable` then

**Comment by TPIvan** [comment]
`IQueryable `is good, but `IEnumerable` would be better. Is there some time estimation for V2?

**Comment by vnbaaij** [comment]
No, no timeline. We have just released the first beta package for V2. Now we need to document all the changes and test (your help appreciated!!) thoroughly.

**Comment by vnbaaij** [comment]
Sorry, but that is just how QuickGrid was designed to work. Not going to change that. Besides, you can just use the `AsQueryable()` extension on an `IEnumerable` to make it work with the grid pretty easily.
