### ISSUE TITLE
fix: multiple regressions in fluent menu, grid and select

### ISSUE THREAD

**Issue by baywet** [microsoft/fast-blazor#245]
# 🐛 Bug Report

Since upgrading from 1.6 rc2 to 2.0-beta1, I've noticed multiple regressions in my application.
First, there is no tag and upgrade guide for this new version on the repo, making it hard to understand whether/what I need to change in my code. (I'm assuming the major bump means breaking changes for my code).

## 💻 Repro or Code Sample

Upgrade an app with a grid, menu and/or select component from 1.6 rc2 to 2.0 beta1

## 🤔 Expected Behavior

My app not to have any regression visually, or at least an upgrade guide.

## 😯 Current Behavior

1. Missing main tag for the grid component when it renders as HTML `<fluent-data-grid generate-header="none" grid-template-columns="1fr 4fr 1fr" id="manualGrid" role="grid" tabindex="0" _bl_78=""><!----><!--!--><!--!--><fluent-data-grid-row row-id="f127e6a3811d6f263" row-index="0" row-type="header" role="row" class="header" _bl_79="" grid-template-columns="1fr 4fr 1fr" style="grid-template-columns: 1fr 4fr 1fr;"><!----><!--!--><fluent-data-grid-cell cell-id="f8c84cbe51b8b1a1" cell-type="columnheader" grid-column="1" tabindex="-1" role="columnheader" class="column-header" _bl_89="" style="grid-column: 1 / auto;">Key</fluent-data-grid-cell><!--!-->`
2. the fluent icons are miss placed, and are using the accent color `<FluentIcon Name="@FluentIcons.Search" Slot="start" Size="@IconSize.Size24" Filled=false UseAccentColor=false />`
3. Fluent Select fails to build unless I provide a Type in the TOption `The type of component 'FluentSelect' cannot be inferred based on the values provided. Consider specifying the type arguments directly using the following attributes`

![image](https://user-images.githubusercontent.com/7905502/200351959-2b220e40-f93b-4352-9944-3495b612ee56.png)
![image](https://user-images.githubusercontent.com/7905502/200352004-6ba12213-d05f-4491-bb35-98c48373250f.png)

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC] windows 11 x64
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox] Edge 107
* .NET and FAST Version [e.g. 1.8.0] 7.0rc2

**Comment by baywet** [comment]
I didn't realize this library was not completely funded, thanks for your support.

1. What I meant it the whole fluent-data-grid tag is missing in the rendered HTML.
2. Thanks, color is fixed. Icons still aren't at the right place (Slot=start)
3. Yes, I'm not sure what motivated this change, but it makes the code a bit more complex, especially when it comes to mapping the value (mapping to an enum in my case)

**Comment by baywet** [comment]
also, would you consider publishing a 1.6.0-rc3 so people can get the benefits of the AOT fix without having to pay the migration cost?

**Comment by vnbaaij** [comment]
I can do that, but the final 1.6 will be out tomorrow (once .NET 7 is released)

**Comment by vnbaaij** [comment]
I can see the tag. Both in the online samples as in your post above:

Missing main tag for the grid component when it renders as HTML 
```
<fluent-data-grid generate-header="none" grid-template-columns="1fr 4fr 1fr" id="manualGrid" role="grid" tabindex="0" _bl_78="">
<!---->
<!--!-->
<!--!-->
<fluent-data-grid-row row-id="f127e6a3811d6f263" row-index="0" row-type="header" role="row" class="header" _bl_79="" grid-template-columns="1fr 4fr 1fr" style="grid-template-columns: 1fr 4fr 1fr;">
<!---->
<!--!-->
<fluent-data-grid-cell cell-id="f8c84cbe51b8b1a1" cell-type="columnheader" grid-column="1" tabindex="-1" role="columnheader" class="column-header" _bl_89="" style="grid-column: 1 / auto;">Key</fluent-data-grid-cell>
```

What am I missing?

**Comment by baywet** [comment]
I can wait until tomorrow then :)

**Comment by vnbaaij** [comment]
> the fluent icons are miss placed, and are using the accent color <FluentIcon Name="@FluentIcons.Search" Slot="start" Size="@IconSize.Size24" Filled=false UseAccentColor=false />

Are you referring to the icons in the `FluentSelect`? I replicated you example in the demo site and I believe it shows as it should:
<img width="199" alt="image" src="https://user-images.githubusercontent.com/1761079/200424698-a7cf74ed-ae2b-4b44-99d2-dd394f1b6ef2.png">

**Comment by vnbaaij** [comment]
> I can wait until tomorrow then :)

I've updated my side of the code. Now I just need to wait for the SDK to become available on the DevOps environment.

If you want a (unsigned) version of the package before that: https://github.com/microsoft/fast-blazor/suites/9185277691/artifacts/428200999

**Comment by baywet** [comment]
The package for devops environment is up (at least for github actions, but I suspect it is as well for ADO)

**Comment by vnbaaij** [comment]
Hi @baywet, just wanted to let you know v2.0.0-RC1 package has been released. I've written an accompanying blogpost that describes more of the breaking changes: https://baaijte.net/blog/microsoft-fast-components-fluentui-2.0/

**Comment by baywet** [comment]
thanks for the follow up, we'll probably wait on the release of this new major before upgrading.
Using a tag here with a link to (or the content) of the blog post would help people upgrading (when coming from a dependabot pull request, or just navigating the repo)
