### ISSUE TITLE
feat: how can i custom styling for FluentSelect?

### ISSUE THREAD

**Issue by JimmyIT** [microsoft/fast-blazor#247]
![image](https://user-images.githubusercontent.com/38621535/201576453-fa496c9a-47d3-40ab-8bbe-b0529b1edf42.png)

this is FluentSelect' DOM is rendered for default applying... 
=> i have a custom class for div > .control and div > .listbox   .... so how can i apply for?
also for the FluentOptions 
For example: 
actual rendered DOM:  
![image](https://user-images.githubusercontent.com/38621535/201577312-03299d39-02e1-42d0-bf80-ca1dc82ce65e.png)

expected rendered DOM
![image](https://user-images.githubusercontent.com/38621535/201577376-597be139-dbdb-4158-9a34-0b22d8dd8242.png)

**Comment by vnbaaij** [comment]
Hi,

This is possible but goes directly against the purpose of this library: supplying components leveraging the Fluent UI design system.

You can target the component with CSS by using the `::deep` selector and then specifying which part of the shadow DOM you want to target by using the standard `::part`selector in your own component's CSS. For example:
```
::deep > fluent-select::part(control){
...your css...
} 
```
