### ISSUE TITLE
datagrid rowfocuse

### ISSUE THREAD

**Issue by ehsangfl** [microsoft/fast-blazor#254]
after upgrade to V2-rc1, I found that `rowfocused` does not raised anymore. so I check code and found that these lines

```
Blazor.registerCustomEventType('cellfocus', {
        browserEventName: 'cell-focused',
        createEventArgs: event => {
            return {
                cellId: event.detail.attributes['cell-id'].value
            };
        }
    });
    Blazor.registerCustomEventType('rowfocus', {
        browserEventName: 'row-focused',
        createEventArgs: event => {
            return {
                rowId: event.detail.attributes['row-id'].value
            };
        }
    });
```

 commented on 
`Microsoft.Fast.Components.FluentUI.lib.module`

are you going to remove it on next release?

**Comment by vnbaaij** [comment]
I found some issues with this when implementing the QuickGrid. Will try it again now that that integration is finished up.

**Comment by ehsangfl** [comment]
after any dom event, we have a rerender process. and this is caused of increasing columns on column
I think we must prevent re render, and handle it on "OnParameterSet"

**Comment by vnbaaij** [comment]
Fixed with merging in your PR. I've made some code changes and added samples to `DataGridTemplateColumns2.razor`
