### ISSUE TITLE
Add Listview, TreeList Controls in Fluent FAST Blazor

### ISSUE THREAD

**Issue by V-AATARE** [microsoft/fast-blazor#256]
# 💬 Add Listview, TreeList Controls in Fluent FAST Blazor

Hi Team,
We have Blazor Server application and currently we are using the 3rd party controls for Blazor.
Due to business requirement, we are planning to shift from 3rd party controls to Fluent Web Components.
So, we have come across this FAST Blazor. We need guidance on below controls that we have extensively used in our application:
1. ListView control with different re-usable templates and pagination features.
2. TreeList control with different re-usable templates and pagination features
3. Import/Export to excel functionality
4. PDF Viewer
5. File Upload control to the storage account.

Also, we need guidance if some of these features are already there that we are not aware?
Or do we have any roadmap to release above controls?

Also need confirmation, are we referring the correct demo site as below:
https://brave-cliff-0c0c93310.azurestaticapps.net/Lab/Header

Please reply asap to take decision from our side.

Thanks,
Aarti Tare

**Comment by vnbaaij** [comment]
Hi Aarti,

First, these Blazor components are still 3rd party components. They come from Microsoft but are **NOT** built and/or supported by the ASP.NET Core team.

1. For ListView I think you could use the DataGrid component (see https://brave-cliff-0c0c93310.azurestaticapps.net/DataGrid). This implements QuickGrid. See https://aspnet.github.io/quickgridsamples/ for more information
2. There is a TreeView component available (https://brave-cliff-0c0c93310.azurestaticapps.net/TreeView). Does not come with pagination features and there are no plans to add that
3. This is not part of the library. You will need to use other 3rd party components for that
4. This is not part of the library. You will need to use other 3rd party components for that
5. This is not part of the library. You will need to use other 3rd party components for that

The demo site you mentioned is the correct site. Al the samples and documentation we have is there. More documentation can also be found at https://learn.microsoft.com/en-us/fluent-ui/web-components/.

We do not have a roadmap available. In general, though we can say there will not be many new components added in the near future. The purpose of the library is to wrap the available Fluent UI Web Components in Blazor. If/When new web component come out, we will add them to the library as well.

p.s. I see this is your first ever issue created on GitHub. May I offer some friendly advice: in general, it is better to not say 'we need' or ask for things 'asap'. Most open-source projects (like this one) only have a few maintainers that do their work in their own time and are not always in a position to jump in to answer/help at your demand.

**Comment by V-AATARE** [comment]
Thanks so much for your quick response.
