### ISSUE TITLE
FluentListbox refuses to trigger any of the onchange logic

### ISSUE THREAD

**Issue by luishdemetrio** [microsoft/fast-blazor#257]
# 🐛 Bug Report

<PackageReference Include="Microsoft.Fast.Components.FluentUI" Version="1.6.0" />

Hi, I am trying to use the FluentListbox with the FluentSearch for autocomplete, but the SelectedOptionChanged is not working.

## 💻 Repro or Code Sample

I am using the following code:

https://brave-cliff-0c0c93310.azurestaticapps.net/Search

<FluentSearch @ref=searchTest 
              @oninput=handleSearchInput 
              
              Value="@searchValue"
              Placeholder="Search for State" />
<br />
<FluentListbox Items=@searchResults TOption="string" SelectedOptionChanged="@(e => searchValue = (e != defaultResultsText ? e : string.Empty) )"  />

## 🤔 Expected Behavior

The SelectedOptionChanged is never called.

**Comment by vnbaaij** [comment]
Sorry, but we'll need more information to be able to help you. Both in the sample you mention and in my own environment it works as expected...

**Comment by luishdemetrio** [comment]
Thank you @vnbaaij for helping me out on this. You are right, I double-check it here and it is working. I will close this one. Thanks again!
