### ISSUE TITLE
fix: FluentAccordion ExpandMode=single does not honour which FluentAccordionItem is expanded

### ISSUE THREAD

**Issue by Andras-Csanyi** [microsoft/fast-blazor#261]
# 🐛 Bug Report

While I was writing bUnit test cases for FluentAccordion and FluentAccordionItem (#250) I found the following interesting case

## 💻 Repro or Code Sample

Consider the following code:
```razor
<FluentAccordion ExpandMode="AccordionExpandMode.Single">
    <FluentAccordionItem>first</FluentAccordionItem>
    <FluentAccordionItem>second</FluentAccordionItem>
    <FluentAccordionItem Expanded="true">third</FluentAccordionItem>
</FluentAccordion>
```

The result is a proper accordion, but the first item is opened not the third one. See the attached screenshot.

<img width="1411" alt="Screenshot 2022-12-11 at 12 22 22" src="https://user-images.githubusercontent.com/5106373/206900705-85a72289-5b81-451b-a83a-ffd2a3b0a843.png">

Moreover,

```razor
<FluentAccordion ExpandMode="AccordionExpandMode.Single">
    <FluentAccordionItem Expanded="false">first</FluentAccordionItem>
    <FluentAccordionItem>second</FluentAccordionItem>
    <FluentAccordionItem>third</FluentAccordionItem>
</FluentAccordion>
```

The code above results the same.

### Additional information

The bUnit tests shows that the generated HTML contains all the necessary information. (This test case checks whether the generated HTML depends on the ExpandMode or not. It does not.) See the snippet below, it will be part of the PR. I assume either my environment setup is wrong (cache for example, but see the following section) or the JS part does something wrong.

```c#
        [Fact]
        public void RenderProperly_WhenExpandedModeIsSingle_AndMultipleItemAreExpanded_ByDefault()
        {
            // Arrange & Act
            IRenderedComponent<FluentUI.FluentAccordion> cut = TestContext.RenderComponent<FluentUI.FluentAccordion>(
                parameters => parameters
                    .Add(p => p.ExpandMode, AccordionExpandMode.Single)
                    .AddChildContent<FluentAccordionItem>(itemParams => itemParams.Add(p => p.Expanded, true))
                    .AddChildContent<FluentAccordionItem>(itemParams => itemParams.Add(p => p.Expanded, true)));
            
            // Assert
            cut.MarkupMatches("<fluent-accordion expand-mode=\"single\">" +
                              "<fluent-accordion-item id:ignore expanded=\"\">" +
                              "<span slot=\"heading\"></span>" +
                              "</fluent-accordion-item>" +
                              "<fluent-accordion-item id:ignore expanded=\"\">" +
                              "<span slot=\"heading\"></span>" +
                              "</fluent-accordion-item>" +
                              "</fluent-accordion>");
        }
```

## 🤔 Expected Behavior

I expect the framework to honour the setup defined in the HTML, meaning if one is marked as `Expanded` the that one should be opened, not the first one.

I also expect the framework to honour that if the first accordion item is marked as `Expanded=false` then it should be closed until the user clicks on it.

## 🌍 Your Environment

- MacOs latest
- `6.0.403 [/usr/local/share/dotnet/sdk]`
- `7.0.100 [/usr/local/share/dotnet/sdk]`
- The example was created by default `Blazor Server App` template and following the install instructions (latest)
- I disabled the cache in the Dev toolbar

**Comment by vnbaaij** [comment]
Regarding the first case, I'm seeing this in the demo environment:
<img width="646" alt="image" src="https://user-images.githubusercontent.com/1761079/207435656-cd37b1fb-57d2-418b-9d6a-d1215ea0d9cc.png">
for the code
```

<FluentAccordion ActiveId="@activeId" OnAccordionItemChange="HandleOnAccordionItemChange">
    <FluentAccordionItem Heading="Panel one">
        <FluentIcon Slot="start" Name="@FluentIcons.Globe" Size="@IconSize.Size20" Color=Color.Neutral />
        Panel one content, using the 'start' slot for extra header content (in this case an icon)
    </FluentAccordionItem>
    <FluentAccordionItem Heading="Panel two">
        <div slot="end">
            #end#
        </div>
        Panel two content, using the 'end' slot for extra header content (in this case an HTML button)
    </FluentAccordionItem>
    <FluentAccordionItem Expanded="true" Heading="Panel three">
        Panel three content
    </FluentAccordionItem>
</FluentAccordion>

<p>Last changed accordion item: @changed?.Heading</p>


@code {
    string activeId = "accordion-1";

    FluentAccordionItem? changed;

    private void HandleOnAccordionItemChange(FluentAccordionItem item)
    {
        changed = item;
    }
}
```

That seems to do what is should.

If I add `Expanded=false` on the first item and remove the `Expanded=true` from the third item, I get this:
<img width="694" alt="image" src="https://user-images.githubusercontent.com/1761079/207436281-d834315b-0db8-450a-b822-b0f36c65d1fb.png">

So, also what is expected...

**Comment by vnbaaij** [comment]
I've also tried this locally in the Server demo. Shows the correct behavior as well. Can you take another look at your test cases? (did you notice it also uses a `class="expanded` part on the fluent-accordion-item when expanded)

Closing this for now.

**Comment by RobDene** [comment]
Hi, I'm noticing similar when I have all accordion items set to expanded=false and expand mode single , the first accordion always opens  and you cannot close it - so there is always 1 accordion item open ?
Latest v4.10.1
