### ISSUE TITLE
feat: Extend Datagrid

### ISSUE THREAD

**Issue by ehsangfl** [microsoft/fast-blazor#263]
I Extended DataGrid component with new features :

1- make it editable with some default columns like `TextboxColumn`, `CheckboxColumn `... with validation functionality
2- new embedded default `ColumnOptions` based on column binding data type, for example, if column data is string, then display a textbox to search, or if datatype is 'Date' then display two datepicker for "`from`" and "`to`" filter
3- extend sort capability, so we can sort by a column, then by another column, then by another ...
4- user can remove sort from a column
5- auto generate column header by `[Display]` attribute on model
6- another way to sort `ColumnOptions` dropdown header similar to `excel` sorting added
7- split sort,filter,display property of column. so a column can display a property, sort by another property, filter by another property, or use same property, if not setted
8- Impoved render performance by setting all parameters of Row and Cells by one setter

if you have a plan or agree to add all these features or some of them, I update my fork and create a PR 
BR

**Comment by vnbaaij** [comment]
Discussion on this has moved to #283
