### ISSUE TITLE
fix: IconService not available in MAUI blazorwebview

### ISSUE THREAD

**Issue by zh4ui** [microsoft/fast-blazor#264]
# 🐛 Bug Report

I'm hosting a blazor web app in a MAUI blazorwebview, see <https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/blazorwebview?source=recommendations&view=net-maui-7.0>.

Since MAUI does not support `builder.Services.AddHttpClient()`, exception raised when visiting a page that contains FluentIcon.

## 💻 Repro or Code Sample

Not available.

## 🤔 Expected Behavior

FluentIcon should be usable in MAUI blazorwebview.

## 😯 Current Behavior

blazor.webview.js raises exception: `Unable to resolve service for type 'System.Net.Http.HttpClient' while attempting to activate 'Microsoft.Fast.Components.FluentUI.IconService'.`

## 🌍 Your Environment

* OS & Device: Windows 11 (update) 
* Browser: BlazorWebview
* .NET and FAST Version: .NET 7 and FAST 1.6.0

**Comment by vnbaaij** [comment]
Are you buidling a MAUI app to run on Windows? Or on other platforms. If so, which?

**Comment by zh4ui** [comment]
> Microsoft.Extensions.Http

Hi, no exception thrown this time, but it's just the icon does not show up.
I created a sample here: <https://github.com/zh4ui/MauiBlazorApp/blob/main/MauiBlazorApp/Pages/Index.razor>

![image](https://user-images.githubusercontent.com/7352394/207373817-c0bc5052-914f-4933-88f1-be7dc6252e36.png)

**Comment by vnbaaij** [comment]
@danroth27 know anyone with more knowledgeable in Maui that could take a look at his?

**Comment by danroth27** [comment]
@zh4ui Can you [open up the browser dev tools for the BlazorWebView](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/developer-tools) and see if there are any errors in the browser dev console?

**Comment by zh4ui** [comment]
Nothing very interesting I'd say

![image](https://user-images.githubusercontent.com/7352394/207591222-6945bbaa-3df1-4d3c-b6ca-02f08c321aef.png)

**Comment by danroth27** [comment]
I tried the same code in a Blazor Server app and I see the same behavior with the icons missing, so this doesn't appear to be Blazor Hybrid specific. 

I also noticed that there are a couple of required parameters for FluentIcon that don't appear to be specified:

![image](https://user-images.githubusercontent.com/1874516/207654757-95e70e4c-f9ef-45e2-8266-c670e0e4b26b.png)

**Comment by zh4ui** [comment]
Hi, adding the missing parameters does not seem to help

```xml
    <FluentButton Appearance="Appearance.Neutral"><FluentIcon Slot="start" Name="@FluentIcons.ArrowCircleLeft" Filled Size="IconSize.Size24" /> Button with icon in 'start' slot</FluentButton>
```

**Comment by vnbaaij** [comment]
I have a fix for this. In the latest commits (targeting 2.0 release) the `IconService` has been renamed to `HttpBasedStaticAssetService`. This is the service that will be used in Blazor Server and Blazor Web Assembly situations. 

For Blazor Hybrid a new `FileBasedStaticAssetService` needs to be added to your Maui/Bazor solution. The file can currently not be added to the library because of dependency on NuGet packages that cannot be included in the Library project. Contents of the file:
```
using System.Net;
using Microsoft.Fast.Components.FluentUI.Infrastructure;

namespace Microsoft.Fast.Components.FluentUI;

public class FileBasedStaticAssetService : IStaticAssetService
{
    private readonly CacheStorageAccessor _cacheStorageAccessor;

    public FileBasedStaticAssetService(CacheStorageAccessor cacheStorageAccessor)
    {
        _cacheStorageAccessor = cacheStorageAccessor;
    }

    public async Task<string> GetAsync(string assetUrl, bool useCache = true)
    {
        string result = null;

        HttpRequestMessage message = CreateMessage(assetUrl);


        if (useCache)
        {
            // Get the result from the cache
            result = await _cacheStorageAccessor.GetAsync(message);
        }

        if (string.IsNullOrEmpty(result))
        {
            //It not in the cache (or cache not used), read the asset from disk
            result = await ReadData(assetUrl);

            if (!string.IsNullOrEmpty(result))
            {

                if (useCache)
                {
                    // If successful, create the response and store in the cache (when used)
                    HttpResponseMessage response = new()
                    {
                        StatusCode = HttpStatusCode.OK,
                        Content = new StringContent(result)
                    };

                    await _cacheStorageAccessor.PutAsync(message, response);
                }
            }
        }

        return result;
    }

    private static HttpRequestMessage CreateMessage(string url) => new(HttpMethod.Get, url);

    private static async Task<string> ReadData(string file)
    {
        using var stream = await FileSystem.OpenAppPackageFileAsync($"wwwroot/{file}");
        using var reader = new StreamReader(stream);

        return await reader.ReadToEndAsync();
    }
}
```
In your `MauiProgram.cs` make sure the following is added before the `return builder.Build()`:

```
builder.Services.AddFluentUIComponents(options =>
{
        options.HostingModel = BlazorHostingModel.Hybrid;
});
builder.Services.AddScoped<IStaticAssetService, FileBasedStaticAssetService>();
```

**Comment by zh4ui** [comment]
Thanks! Can't wait to see 2.0 release.
