### ISSUE TITLE
fix: FluentSelect does not update when SelectedOption updates.

### ISSUE THREAD

**Issue by Terrence77** [microsoft/fast-blazor#266]
I am using Next and Previous buttons to cycle through the Select.

When I hit Next, Next the Select updates fine.

When I hit Previous, Previous it does not update.

The SelectedOption is being changed in code from the buttons.

Here is the code

`
@page "/"

<div style="z-index:2; position: relative;">

	<FluentButton Appearance="Appearance.Accent" @onclick="Previous">Previous</FluentButton>

	<FluentSelect TOption="Article2"
				  SelectedOptionChanged="@SelectionMade"
				  SelectedOption="@SelectedArticle"
				  Items="@Articles"
				  Id="artListBox"
				  OptionText="@(a => a.Name)"
				  Position="SelectPosition.Below" />

	<FluentButton Appearance="Appearance.Accent" @onclick="Next">Next</FluentButton>
</div>

@code {
	public class Article2
	{
		public string Name { get; set; }
	}

	public Article2 SelectedArticle { get; set; }
	public List<Article2> Articles { get; set; }

	public int ArticleIndex { get; set; } = 0;

	protected override void OnInitialized()
	{
		LoadArticles();
	}
	private void Next()
	{
		++ArticleIndex;
		SelectedArticle = Articles[ArticleIndex];
	}
	private void Previous()
	{
		--ArticleIndex;
		SelectedArticle = Articles[ArticleIndex];
	}
	private void SelectionMade(Article2 selectedArticle)
	{
		SelectedArticle = selectedArticle;
		ArticleIndex = Articles.IndexOf(selectedArticle);
	}

	private void LoadArticles()
	{
		Articles = new List<Article2>
		{
			new Article2{Name = "One"},
			new Article2{Name = "Two"},
			new Article2{Name = "Three"},
			new Article2{Name = "Four"},
			new Article2{Name = "Five"},
		};
	}

}

`

**Comment by vnbaaij** [comment]
Hi,
I spent a considerable amount of time on trying to fix this but can't get it to work 😢.
The 'Next' button seems to work but once you select an actual entry from the list, that button gets 'disconnected' as well.

Sorry, but I'm closing this as it is quite a niche way of working with a Select list component.

**Comment by guillaume-brouillon** [comment]
Don't you just need to link current-value from <fluent-select> to the razor component's Value property ?
This seems to work in this scenario : 
`@namespace Microsoft.Fast.Components.FluentUI
@inherits ListComponentBase<TOption>
@typeparam TOption
<CascadingValue Value="_internalListContext" Name="ListContext" TValue="InternalListContext<TOption>" IsFixed="true">
    <fluent-select @ref=Element
                   id=@Id
                   class="@ClassValue"
                   style="@StyleValue"
                   open="@Open"
                   position="@Position.ToAttributeValue()"
                   multiple="@Multiple"
                   disabled="@Disabled"
                   appearance="@Appearance.ToAttributeValue()"
                   aria-label="@(!string.IsNullOrWhiteSpace(Title) ? Title : "")"
                   current-value="@Value"
                   @onchange="@OnChangedHandlerAsync"
                   @attributes="AdditionalAttributes">
       @GetListOptions(Items)
    </fluent-select>
</CascadingValue>`

`@inject DataSource Data

<label for="people-listbox">Select a person</label>
<FluentSelect TOption="Person"
              Items="@Data.People"
              Id="people-listbox"
              OptionValue="@(p => p.PersonId.ToString())"
              OptionText="@(p => p.LastName + ", " + p.FirstName)"
              @bind-Value="@SelectedValue"
              @bind-SelectedOption="@SelectedPerson" />

<FluentButton @onclick="GoNext">Next</FluentButton>
<FluentButton @onclick="GoPrevious">Previous</FluentButton>

<p>
    Selected value: @SelectedValue <br />
    Selected person (strongly typed): @SelectedPerson?.ToString()
</p>

@code
{
    int current_index = 4;
    void GoNext()
    {
        current_index = current_index + 1 < Data.People.Count() ? current_index + 1 : current_index;
        SelectedValue = current_index.ToString();
    }
    void GoPrevious()
    {
        current_index = current_index - 1>0 ? current_index - 1 : 0;
        SelectedValue = current_index.ToString();
    }
    Person? SelectedPerson;
    string? SelectedValue = "4";
}`
