### ISSUE TITLE
fix: FluentSelect does not update when SelectedOption changes...

### ISSUE THREAD

**Issue by Terrence77** [microsoft/fast-blazor#269]
I am using Next and Previous buttons to cycle through the Select.
When I hit Next, Next the Select updates fine.
When I hit Previous, Previous it does not update.
The SelectedOption is being changed in code from the buttons.

Here is the code.
`
@page "/"

<div style="z-index:2; position: relative;">

	<FluentButton Appearance="Appearance.Accent" @onclick="Previous">Previous</FluentButton>

	<FluentSelect TOption="Article2"
				  SelectedOptionChanged="@SelectionMade"
				  SelectedOption="@SelectedArticle"
				  Items="@Articles"
				  Id="artListBox"
				  OptionText="@(a => a.Name)"
				  Position="SelectPosition.Below" />

	<FluentButton Appearance="Appearance.Accent" @onclick="Next">Next</FluentButton>
</div>

@code {
	public class Article2
	{
		public string Name { get; set; }
	}

	public Article2 SelectedArticle { get; set; }
	public List<Article2> Articles { get; set; }

	public int ArticleIndex { get; set; } = 0;

	protected override void OnInitialized()
	{
		LoadArticles();
	}
	private void Next()
	{
		++ArticleIndex;
		SelectedArticle = Articles[ArticleIndex];
	}
	private void Previous()
	{
		--ArticleIndex;
		SelectedArticle = Articles[ArticleIndex];
	}
	private void SelectionMade(Article2 selectedArticle)
	{
		SelectedArticle = selectedArticle;
		ArticleIndex = Articles.IndexOf(selectedArticle);
	}

	private void LoadArticles()
	{
		Articles = new List<Article2>
		{
			new Article2{Name = "One"},
			new Article2{Name = "Two"},
			new Article2{Name = "Three"},
			new Article2{Name = "Four"},
			new Article2{Name = "Five"},
		};
	}

}

`

**Comment by vnbaaij** [comment]
What is different here than with #266? Did you miss my response there?

**Comment by tpspencer** [comment]
I am sorry, I do not know why I re-opened the issue.

**Comment by vnbaaij** [comment]
No worries! Will do.
