### ISSUE TITLE
fix: alignment in datagrid

### ISSUE THREAD

**Issue by chucker** [microsoft/fast-blazor#270]
# 🐛 Bug Report
The new QuickGrid-derived DataGrid in 2.0.0rc1 exposes an `Align` property on columns, but it doesn't currently seem to have an effect.

## 💻 Repro or Code Sample

```razor
    <FluentDataGrid RowsData="@MyCollection.AsQueryable()">
        <PropertyColumn Property="@(p => p.Title)" Sortable="true" Align="Align.Center" />

        <PropertyColumn Property="@(p => p.Amount)" Sortable="true"
                        Align="Align.Right" Format="c2" />
    </FluentDataGrid>
```

## 🤔 Expected Behavior

The second column should be right-aligned.

## 😯 Current Behavior

There are two columns, but both are left-aligned.

<img width="511" alt="image" src="https://user-images.githubusercontent.com/20194/208878272-ef95db39-e271-47fe-b258-8ef500ae3ee0.png">

## 🔦 Context

This is for a simple data grid for an accounting application that lists checking accounts and their current balances.

## 🌍 Your Environment

* **OS & Device:** macOS 13.1 on M1 Pro
* **Browser:** Safari Version 16.2 (18614.3.7.1.5)
* **.NET and FAST Version:** Blazor WASM 7.0.1, FAST 2.0.0-rc1

**Comment by vnbaaij** [comment]
Hmm, must be a Safari thing. This is what I get 
<img width="334" alt="image" src="https://user-images.githubusercontent.com/1761079/209007280-d8bb4a7f-28e7-4778-8a4d-8d37ebd1e3ab.png">

when changing the `DataGridGetStarted` sample in the demo site to  
```
<FluentDataGrid RowsData="@people">
    <PropertyColumn Property="@(p => p.PersonId)" Sortable="true" Align="Align.Center" />
    <PropertyColumn Property="@(p => p.Name)" Sortable="true" Align="Align.Right"/>
</FluentDataGrid>
```

I do not have a mac to test with. Not sure how to proceed with this...

**Comment by chucker** [comment]
Hm, no, I see it in Chrome 108 as well:

<img width="930" alt="image" src="https://user-images.githubusercontent.com/20194/209011831-bcdb0666-d010-472a-b291-4f0b5c493612.png">

Could it be a side effect of https://github.com/microsoft/fast-blazor/commit/d85d92242870ce7754dcc927512129edac9a9059#diff-85c3e008f81d1605e29eeaaed4f72138b041eed708d76831a350e233305e1bcc? That seems to change the CSS of the components a fair bit, so you're testing against a pre-RC2, whereas I have RC1.

(Is RC2 coming soon and/or are there nightly builds?)

**Comment by vnbaaij** [comment]
Those changes should have been in RC1 already. I'll check.

Just released RC2: https://github.com/microsoft/fast-blazor/discussions/274. Package is available on NuGet: https://www.nuget.org/packages/Microsoft.Fast.Components.FluentUI/2.0.0-rc-2 (might not show up in searches yet)

**Comment by vnbaaij** [comment]
This is in Edge 108:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/1761079/209019039-1de3f351-3b6e-4f4b-a999-5d3c6fd0d83f.png">

**Comment by chucker** [comment]
Never mind, my bad.

The issue was that this particular style is provided via scoped CSS, which I had disabled because I didn't need ti yet. Uncommenting

```html
    <link href="MyApp.Client.styles.css" rel="stylesheet" />
```

did the trick.

It might be worth pointing this out in the README, though: if you create a Blazor app with the `blazorwasm-empty` template, its `index.html` will contain something like:

```html
    <!-- If you add any scoped CSS files, uncomment the following to load them-->
    <link href="MyApp.Client.styles.css" rel="stylesheet" /> 
```

If fast-blazor assumes that scoped CSS is enabled the Readme should probably include instructions to enable it.
