### ISSUE TITLE
feat: add decimal alignment to datagrid

### ISSUE THREAD

**Issue by chucker** [microsoft/fast-blazor#271]
# 🙋 Feature Request

In 2.0.0-rc1, columns support an align property. It would be nice if this allowed you to align by the decimal point, e.g. the second column here:

```
| Bank Account | Balance    |
|--------------|------------|
| Aaa          |    $123.45 |
| Bbb Cc       |  $1,000.00 |
```

In proportional fonts, merely right-aligning isn't quite the same.

CSS [_sort of_ supports this](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align), but that's only for tables, which I believe datagrid doesn't currently render as:

>/* Character-based alignment in a table column */
>text-align: ".";
>text-align: "." center;

## 🔦 Context

This is for a data grid that lists accounting information.

(This issue may also be more appropriate for the upstream QuickGrid repo?)

**Comment by vnbaaij** [comment]
You are correct in that we do not uses tables for rendering the grid (QuickGrid itself does btw). Tḣe CSS based alignment does not work.
I'm afraid your only solution at this time is to use a proportional font for that kind of data and right align the column.
Closing this as 'won't (can't) fix'
