### ISSUE TITLE
feat: Add panel/drawer component

### ISSUE THREAD

**Issue by juho-hanhimaki** [microsoft/fast-blazor#278]
# 🙋 Feature Request

I wish the library would include panel/drawer component similar to:
https://developer.microsoft.com/en-us/fluentui#/controls/web/panel

It should have the option to be dismissible by clicking outside the panel area / escape key.

It would make building applications with notification/setting panels easy.

![image](https://user-images.githubusercontent.com/12390182/209863323-9fa321dc-8cff-46c1-b735-ff8cbc713219.png)

**Comment by vnbaaij** [comment]
If this is added, it will not become part of the library itself yet. It would become part of the incubation lab in the demo environment first. Would you still like to have it then?
If yes, I have code that I can most probably re-use from an internal project. I will take a look at how much effort would be involved. Anyways, I won't start on it till after the final 2.0 release (which no date has been set for yet)

**Comment by juho-hanhimaki** [comment]
I did end up repurposing the `FluentDialog` component with some custom CSS as it so happens the Dialog component has the desired behaviour (dismissable, captures focus). Just needed some custom CSS for layout.

So I wouldn't say this is anything super important for me at this point. But having an built in solution for side panels would certainly be useful to get people building useful stuff faster.

```
::deep > fluent-dialog::part(positioning-region) {
    justify-content: initial;
}

::deep > fluent-dialog::part(control) {
    height: initial;
    width: auto;
    margin: 0;
    border-radius: 0;
    border: 0;
}

::deep fluent-menu {
    box-shadow: none;
    border-radius: 0;
}
```
<img width="234" alt="image" src="https://user-images.githubusercontent.com/12390182/210020951-c7817610-da7c-4f25-8ddd-40854a073fec.png">

**Comment by vnbaaij** [comment]
Just putting this here for posterity, panels are now part of the library (v3)
