### ISSUE TITLE
feat: Make MenuButton menu dismissible by esc/click outside the menu

### ISSUE THREAD

**Issue by juho-hanhimaki** [microsoft/fast-blazor#279]
# 🙋 Feature Request

The usability of MenuButton could be enhanced by making the menu dismissible by keyboard or clicking outside the menu.

I don't know of an instance where the current would be desirable.

See:
https://brave-cliff-0c0c93310.azurestaticapps.net/Lab/MenuButton

The enhancement would make building applications with components such as account menu much easier.

![image](https://user-images.githubusercontent.com/12390182/209864139-ef218067-40ff-4f9c-9731-7a14c1a2aa14.png)

**Comment by vnbaaij** [comment]
Both dismissible by keyboard (escape) and clicking outside the menu now work. See the example in the demo site. 

Had to add a bit of JavaScript interop so there is now also a `MenuButton.js` file that needs to be copied to get this working in your own project. Remember to update the path to this collocated file in your own source!
