### ISSUE TITLE
feat: Consider moving FluentDataGrid to another namespace

### ISSUE THREAD

**Issue by juho-hanhimaki** [microsoft/fast-blazor#281]
# 🙋 Feature Request

I am opting not to use the provided FluentDataGrid as it is not html table based (uses per row css grid instead). Instead I am now using the standard QuickGrid.

However using it is quite painful because namespace collisions.

In my _Imports.razor I have.
```
@using Microsoft.AspNetCore.Components.QuickGrid
@using Microsoft.Fast.Components.FluentUI
```

Now the following code won't work as TemplateColumn and PropertyColumn exists in both imported namespaces.
```
        <QuickGrid Items="@(Filter())" Virtualize="true">
            <TemplateColumn Title="Name"></TemplateColumn>
            <PropertyColumn Title="Date created" Property="@(c => c.CreatedTimestamp)" Format="yyyy-MM-dd" Sortable="true"></PropertyColumn>
        </QuickGrid>
```
So now I need to go with the fully qualified format which is just tedious.
```
        <QuickGrid Items="@(Filter())" Virtualize="true">
            <Microsoft.AspNetCore.Components.QuickGrid.TemplateColumn Title="Name"></Microsoft.AspNetCore.Components.QuickGrid.TemplateColumn>
            <Microsoft.AspNetCore.Components.QuickGrid.PropertyColumn Title="Date created" Property="@(c => c.CreatedTimestamp)" Format="yyyy-MM-dd" Sortable="true"></Microsoft.AspNetCore.Components.QuickGrid.PropertyColumn>
        </QuickGrid>
```
Having the FAST component's custom PropertyColumn and TemplateColumn and possible other conflicting implementations in different namespace from the main namespace `Microsoft.Fast.Components.FluentUI` would greatly help with working with the standard QuickGrid.

**Comment by vnbaaij** [comment]
> Having the FAST component's custom PropertyColumn and TemplateColumn and possible other conflicting implementations in different namespace from the main namespace Microsoft.Fast.Components.FluentUI would greatly help with working with the standard QuickGrid.

But that would also mean that everyone else needs to do extra work when they just want to use the `FluentDataGrid` (add namespace to `_imports.cs` or add `@using` etc), we need to document it, add setup instructions, etc.

I agree that having to use the full namespace in your situation is a bit cumbersome and tedious, but it seems to be a bit of an edge case and I don't want to have others do extra work needed to support this. Also, by using the full namespace, it is totally clear that you are not using Fluent library functionality and code,

**Comment by vnbaaij** [comment]
> Having the FAST component's custom PropertyColumn and TemplateColumn and possible other conflicting implementations in different namespace from the main namespace Microsoft.Fast.Components.FluentUI would greatly help with working with the standard QuickGrid.

But that would also mean that everyone else needs to do extra work when they just want to use the `FluentDataGrid` (add namespace to `_imports.cs` or add `@using` etc), we need to document it, add setup instructions, etc.

I agree that having to use the full namespace in your situation is a bit cumbersome and tedious, but it seems to be a bit of an edge case and I don't want to have others do extra work needed to support this. Also, by using the full namespace, it is totally clear that you are not using Fluent library functionality and code,
