### ISSUE TITLE
docs: add documentation for data grid entity framework integration

### ISSUE THREAD

**Issue by nikolayarhangelov-arnitek** [microsoft/fast-blazor#285]
Assigning a DbSet to the FluentDataGrid will throw an exception stating _you must call AddFluentDataGridEntityFrameworkAdapter on your service collection_. There is no documentation that describes what needs to be done in this case.

# Steps to Reproduce
Create a very basic Blazor server application with Entity Framework and pass a DbSet to the data grid's _RowsData_ property.
You will encounter the following exception: _The supplied {queryable} is provided by Entity Framework. To query it efficiently, you must call AddFluentDataGridEntityFrameworkAdapter on your service collection._

FluentDataGrid source code with exception: [AsyncQueryExecutorSupplier.cs](https://github.com/microsoft/fast-blazor/blob/38ee5fb06bfba3770c31e1a65a818c716d19bcd4/src/Microsoft.Fast.Components.FluentUI/Components/DataGrid/Infrastructure/AsyncQueryExecutorSupplier.cs#L38)

# 🙋 Documentation Request
Create documentation how to integrate Entity Framework with FluentDataGrid.
Note that there are no other mentions of _AddFluentDataGridEntityFrameworkAdapter_ in the FluentDataGrid source code or documentation.

## 💁 Possible Solution
Implement your own _IAsyncQueryExecutor_ and register it in the application.
``` csharp
public class EntityFrameworkQueryExecutor : IAsyncQueryExecutor
{
    private const string _efCoreProvider = "Microsoft.EntityFrameworkCore.Query.IAsyncQueryProvider";
    
    public bool IsSupported<T>(IQueryable<T> queryable) =>
        queryable
            .GetType()
            .GetInterfaces()
            .Any(x => string.Equals(x.FullName, _efCoreProvider)) == true;

    public Task<int> CountAsync<T>(IQueryable<T> queryable) => queryable.CountAsync();

    public Task<T[]> ToArrayAsync<T>(IQueryable<T> queryable) => queryable.ToArrayAsync();
}
```

``` csharp
builder.Services.AddTransient<IAsyncQueryExecutor, EntityFrameworkQueryExecutor>();
```

**Comment by vnbaaij** [comment]
You are correct. The EF provider has not been added to the library yet. Will do that for version 2.1. It was not addedy because with QuickGrid it was a separate package and I can't easily add a new package. 

With the 2.0 version we have the foundation in place to work with configuration and options when adding the services to the DI container. I'll add the required things there.

In the meantime your workaround is a solid one!

Thanks for reminding me to put this on the to do list.

**Comment by nikolayarhangelov-arnitek** [comment]
Thank you for the quick response @vnbaaij ! I was very excited to learn that there is a FluentUI implementation for Blazor. Keep up the great work!

**Comment by vnbaaij** [comment]
Looking at integrating this. As I understand your code, adding your workaround only works when you have added the EF packages to your project. Correct?

**Comment by nikolayarhangelov-arnitek** [comment]
Yes, the workaround only works with the EF packages. The workaround itself is simple and straightforward, so adding a new package will probably be overkill.
I think it would be sufficient to document it.

**Comment by vnbaaij** [comment]
It is indeed a bit of overkill, but it makes the process of adding the EF support more robust and foolproof (especially for the novice users). Looking at it from this angle and also from a support perspective, I'll go ahead and add a package for it. Thanks for your feedback!

I thought it would be hard for me to add a new package but turns out I can do it fairly easy. Will post here when it's done.

**Comment by vnbaaij** [comment]
Would you be willing to test the package before I publish it? If so, can you let me know how I can best get the package to you? Thanks!

**Comment by nikolayarhangelov-arnitek** [comment]
Yes, I'll be more than happy to assist :)

**Comment by vnbaaij** [comment]
Thanks. Please try this package (it is not a signed package yet) https://github.com/microsoft/fast-blazor/releases/download/V2.0.0/Microsoft.Fast.Components.FluentUI.DataGrid.EntityFrameworkAdapter.2.0.0.nupkg
There is a readme included. Basically, just install and add `builder.Services.AddDataGridEntityFrameworkAdapter();`

**Comment by vnbaaij** [comment]
Or you can try the published package: https://www.nuget.org/packages/Microsoft.Fast.Components.FluentUI.DataGrid.EntityFrameworkAdapter

**Comment by vnbaaij** [comment]
Fixed with the new package and Readme updates

**Comment by nikolayarhangelov-arnitek** [comment]
I can confirm that the package is working. Thank you for resolving this so quickly, Vincent!
