### ISSUE TITLE
Datagrid PropertyColumn Sortable property error when there are no value

### ISSUE THREAD

**Issue by chigivigi** [microsoft/fast-blazor#291]
# 🐛 Bug Report

I use a DataGrid to display a list of records. Some records have null values for some properties. The DataGrid returns an error when displaying the grid where a column that has sortable enabled but not all records have values for that column.

There is another error that the column name is not displayed when all the records do not have a value for that column.

Unhandled exception rendering component: Arg_NullReferenceException

## 💻 Repro or Code Sample

Create a DataGrid that  has three columns, use PropertyColumn element for defining the columns.
Create a record that has three string properties.
Create a record list property and give it some values. Make sure that at least one record you pass to the list has one property not defined.

For the second error make sure that all records of a list do not have a value for the same column.

## 🤔 Expected Behavior

The page does not break and show error messages. If all values of a column are empty the column does not sort the records based on that column but the column name is visible.

## 😯 Current Behavior

The DataGrid returns an error message and the page breaks. The column is not visible.

## 🔦 Context

There are times when records do not have values for specific properties because the properties were added to the entity after the record was already created or the properties are empty until a specific criteria is not met.

## 🌍 Your Environment

Visual Studio 2022
Net6.0
Microsoft Edge Version 108.0.1462.76 (Official build) (64-bit)
Windows 11
fast-blazor version 2.0.0.0

**Comment by hkusulja** [comment]
Also interested in fix.

**Comment by vnbaaij** [comment]
For the first error, I'm trying this code to reproduce:
```
<FluentDataGrid RowsData="@people">
    <PropertyColumn Property="@(p => p.first)" Sortable="true" />
    <PropertyColumn Property="@(p => p.last)" Sortable="true" />
    <PropertyColumn Property="@(p => p.city)" Sortable="true" />
</FluentDataGrid>

@code {
    record Person(string first, string last, string? city);

    IQueryable<Person> people = new[]
    {
        new Person("Jean","Martin", "Delft"),
        new Person("António","Langa", "Den Hoorn"),
        new Person("Julie","Smith", null ),
        new Person("Nur","Sari", "Den Haag" ),
        new Person("Jose","Hernandez", "Zoetermeer"),
        new Person("Kenji","Sato", "Pijnacker")
    }.AsQueryable();
}
```
This gives me the expected result of:
<img width="637" alt="image" src="https://user-images.githubusercontent.com/1761079/212116223-78d40409-747e-4459-80f5-520cf200d708.png">

I can sort on city and then the row with 'null'is shown on top. Am I missing something?

**Comment by chigivigi** [comment]
I looked at my code again and found the problem after seeing your examples, the problem was in the template column element where I passed a grid sort property using a different model that the one defined when passing the rowadata. After making that change I am not receiving the  null reference exception.
