### ISSUE TITLE
fix: [Fluent Multiselect Unselections] in [Fluent Multi Select]

### ISSUE THREAD

**Issue by bLinMil** [microsoft/fast-blazor#2931]
# 🐛 Bug Report

## 💻 Repro or Code Sample

```
<FluentSelect Items="_opStatus"
              TOption="(string, bool?)"
              OptionText="i => i.Item1"
              OptionValue="i => i.Item2?.ToString()"
              Width="300px"
              Height="200px"
              Multiple="true"
              SelectedOptionsChanged="@(async (e) => await HandleStatusFilters(e, index, operation))"
              SelectedOptions="_selectedStatusFilters.ContainsKey(operation) ? _selectedStatusFilters[operation] : null">

</FluentSelect>
```

## 🤔 Expected Behavior

When I deselect the last element, SelectedOptionsChanged should fire and provide me with an empty list.

## 😯 Current Behavior

When I select one thing or multiple things, the HandleStatusFilters event handler for SelectedOptionsChanged will fire and return me a list<T> where T=>(string, bool?) tuple of size 1 up to n. However, if I start deselecting my elements, the method will still fire with 1 less element in the list up until the last element is deselected.

When the last element is deselected, it is not returning an empty list, but a list with count 1 which contains the last remaining element that was then deselected.

## 💁 Possible Solution

return an empty list if I deselect everything.

## 🔦 Context

I have a check for filtering where if I select nothing or if I select everything, I skip over filtering because it is essentially asking for everything so why bother going through the filtering.  It works when everything is selected, but when nothing is selected, it is still giving me a list of 1 element. I would expect an empty list.

## 🌍 Your Environment

Windows 10, using Edge. 
.Net 8.0.404

**Comment by vnbaaij** [comment]
As can be seen in this example https://www.fluentui-blazor.net/Select#multipleitems, `SelectedItems` is empty if no more items are selected. 

You should change your code to use `@bind-SelectedOptions` and `@bind-SelectedOptions:after`

**Comment by bLinMil** [comment]
Sure, thank you for the help!

**Comment by bLinMil** [comment]
<FluentSelect Items="_opStatus"
              TOption="(string, bool?)"
              OptionText="i => i.Item1"
              OptionValue="i => i.Item2?.ToString()"
              Width="300px"
              Height="200px"
              Multiple="true"
              @bind-SelectedOptions="@_selectedStatusFilters[operation]"
              @bind-SelectedOptions:after="HandleStatusFilters(index, operation)">
</FluentSelect>

Binding seems to work ok, however, I am getting the error for bind-SelectedOptions:after argument 1: cannot convert from 'system.threading.tasks.task' to 'system.action'

**Comment by vnbaaij** [comment]
You have not supplied reproduction code we can run. We don't look at issues that we need to supply and Co me up with sample code.

**Comment by bLinMil** [comment]
Right, let me try and give more contextual code:

Heres the markup 
<TemplateColumn Filtered="_selectedStatusFilters[operation].Count() > 0" Title="@operation" Align="@Align.Center" Width="80px" Style="margin-top: 2px; padding-top: 0;">
    <ColumnOptions>
        <FluentSelect Items="_opStatus"
                      TOption="(string, bool?)"
                      OptionText="i => i.Item1"
                      OptionValue="i => i.Item2?.ToString()"
                      Width="300px"
                      Height="200px"
                      Multiple="true"
                      @onchange="@(async e => {
                      if (_selectedStatusFilters[operation].Count() == 0)
                      {
                        await HandleStatusFilters(index, operation);
                      }
                      })"
                      @bind-SelectedOptions="@_selectedStatusFilters[operation]"
                      @bind-SelectedOptions:after="async () => await HandleStatusFilters(index, operation)">
        </FluentSelect>
    </ColumnOptions>
    <ChildContent>
        @PartStatus(context.Statuses.ToList()[index])
    </ChildContent>
</TemplateColumn>

Here's the bound data structure 
private Dictionary<string, IEnumerable<(string, bool?)>> _selectedStatusFilters = new();


Here's handleStatusFilters

private async Task HandleStatusFilters(int index, string opName)
{
    var selectedItems = _selectedStatusFilters[opName];

    if (selectedItems.Count() > 0 && selectedItems.Count() < 3) // if the user wants to filter for 1-2 statuses
    {
        // define the delegate
        Func<PartLocation, bool> predicate = (p => selectedItems.Select(x => x.Item2).Contains(p.Statuses.ToList()[index]));

        // if add it to the dictionary
        if (_statusFilters.ContainsKey(opName))
        {
            _statusFilters[opName] = predicate;
        }
        else
        {
            _statusFilters.Add(opName, predicate);
        }
    }
    else // otherwise it's like they're not filtering so just remove the delegate
    {
        if (_statusFilters.ContainsKey(opName))
        {
            _statusFilters.Remove(opName);
        }
    }
    await _gridRef!.RefreshDataAsync();
}

When I change my selected values, I can see while debugging that it is correctly binding the the entries in my dictionary, in this case lets call each key OPERATION_{N}.  When I select a from a, b, c for column OPERATION_1 for example, the associated entry in the dictionary will have list(a).  When I unselect (a) then I try and set a break point, I can see it is now empty.

But the issue is, in the method HandleStatusFilters, it should be called when I deselect the LAST remaining selected element. It is not it seems. However, it it binding the the dictionary entry an empty list when I DESELECT it. I'm not sure what is going on.

Some more context, I am using a FluentDataGrid using an items provider which is providing me a list of filtering objects from the filtering mechanism from above:


<FluentDataGrid Class="gridReport" @ref=_gridRef TGridItem="PartLocation" ItemsProvider="_partLocationsItemsProvider" Virtualize="true" ItemSize="28" GenerateHeader="GenerateHeaderOption.Sticky" Style="min-width: max-content;">
    <PropertyColumn Title="Serial Number" Property="@(c => c.SerialNumber)" Sortable="true" Filtered="!string.IsNullOrWhiteSpace(_serialNumberFilter)">
        <ColumnOptions>
            <div>
                <FluentTextField type="search" @bind-Value="@_serialNumberFilter" @oninput='(async (e) => await HandleStringFilters(e, "serialNumber"))' Placeholder="Serial Number" />
            </div>
        </ColumnOptions>
    </PropertyColumn>

    <PropertyColumn Title="Customer Serial Number" Property="@(c => c.CustomerSerialNumber)" Filtered="!string.IsNullOrWhiteSpace(_customerSerialNumberFilter)">
        <ColumnOptions>
            <div>
                <FluentTextField type="search" @bind-Value="@_customerSerialNumberFilter" @oninput='(async (e) => await HandleStringFilters(e, "customerSerialNumber"))' Placeholder="Customer Serial Number" />
            </div>
        </ColumnOptions>
    </PropertyColumn>

    <PropertyColumn Title="Start Date" Width="190px" Style="margin-top: 2px; padding-top: 0;" Property="@(item => item.StartTime)" Filtered="(_startDateFilter != null)">
        <ColumnOptions>
            <div>
                <FluentCalendar SelectMode="CalendarSelectMode.Single" @bind-Value="@_startDateFilter" @bind-Value:after='(async () => await HandleDateFilters("startDate"))' />
            </div>
            <div>
                <FluentButton @onclick="HandleClearStartDate">Clear Date Filter</FluentButton>
            </div>
        </ColumnOptions>
    </PropertyColumn>

    <PropertyColumn Title="Completed Date" Width="180px" Style="margin-top: 2px; padding-top: 0;" Property="@(item => item.CompleteTime)" Filtered="(_completeDateFilter != null)">
        <ColumnOptions>
            <div>
                <FluentCalendar SelectMode="CalendarSelectMode.Single" @bind-Value="@_completeDateFilter" @bind-Value:after='(() => HandleDateFilters("completedDate"))' />
            </div>
            <div>
                <FluentButton @onclick="HandleClearCompleteDate">Clear Date Filter</FluentButton>
            </div>
        </ColumnOptions>
    </PropertyColumn>
    @foreach (var (operation, index) in _operations.Select((operation, index) => (operation, index)))
    {
        <TemplateColumn Filtered="_selectedStatusFilters[operation].Count() > 0" Title="@operation" Align="@Align.Center" Width="80px" Style="margin-top: 2px; padding-top: 0;">
            <ColumnOptions>
                <FluentSelect Items="_opStatus"
                              TOption="(string, bool?)"
                              OptionText="i => i.Item1"
                              OptionValue="i => i.Item2?.ToString()"
                              Width="300px"
                              Height="200px"
                              Multiple="true"
                              @onchange="@(async e => {
                              if (_selectedStatusFilters[operation].Count() == 0)
                              {
                                await HandleStatusFilters(index, operation);
                              }
                              })"
                              @bind-SelectedOptions="@_selectedStatusFilters[operation]"
                              @bind-SelectedOptions:after="async () => await HandleStatusFilters(index, operation)">
                </FluentSelect>
            </ColumnOptions>
            <ChildContent>
                @PartStatus(context.Statuses.ToList()[index])
            </ChildContent>
        </TemplateColumn>
    }
</FluentDataGrid>

**Comment by vnbaaij** [comment]
Sorry, but this is still not ready to run code. Please use properly formatted code (use ``` to start and end code blocks), Also, I only need _minimal_ code needed to reproduce the issue at hand. 

From what I am seeing, you are using selects in a datagrid. With how many rows? This seems like a recipe for failure that will lead to a slow page because of all the code generated We have already mentioned a lot of times that a grid is better not used as an Excel like data entry component,

**Comment by bLinMil** [comment]
```<h3>MySelect</h3>

<FluentStack Orientation="Orientation.Horizontal" Style="height: 400px">
    @foreach (var entry in _test.Keys)
    {
        <FluentSelect TOption="SelectOption"
                      Items="_allItems"
                      Multiple="true"
                      Autofocus="true"
                      OptionText="item => item.Text"
                      OptionValue="item => item.Value"
                      @bind-SelectedOptions='_test[entry]'
                      @bind-SelectedOptions:after="() => DoSomething(entry)" />
    }
    
    <FluentLabel>Options selected @_total</FluentLabel>
</FluentStack>

@code
{

    private Dictionary<string, IEnumerable<SelectOption>?> _test = new() { { "Line01", null }, { "Line02", null } };

    private IEnumerable<SelectOption> _allItems = new List<SelectOption>()
    {
        new() { Text="Line01", Value="1" },
        new() { Text="Line02", Value="2" },
        new() { Text="Line03", Value="3" },
        new() { Text="Line04", Value="4" },
        new() { Text="Line05", Value="5" },
        new() { Text="Line06", Value="6" },
    };

    private void DoSomething(string entry)
    {
        
        return;
    }

    private IEnumerable<SelectOption>? _selectedItems;

    private int _total;

    private void HandleSelectedOptionsChanged(IEnumerable<SelectOption>? items)
    {
        _test["Line01"] = items;

        _total = items?.Count() ?? 0;
    }

    private class SelectOption
    {
        public string Text { get; set; }
        public string Value { get; set; }
    }
}```

I got a small example working. It looks like it is bound to the correct dictionary entry. However, I did notice, when I select my first entry, the DoSomething() method fires once, but If I select again or select more than 1 it fires twice in succession.  Also happens when deselecting

**Comment by vnbaaij** [comment]
Sorry, but I have no idea on what you are trying to do with that code. It makes no sense at all. I can only suggest you look at the code example I posted earlier. Multi select is working there as it should. 
I already closed this issue so won't be commenting on it anymore.
