### ISSUE TITLE
Is there any way to change styling of Treeview control?

### ISSUE THREAD

**Issue by V-AATARE** [microsoft/fast-blazor#296]
Is there any way to change the styling of treeview like font-size, back-ground color, open, collapse icons?
# 🙋 Feature Request

Need requirement to change font-size and color of treeview. 
Currently using following java script function to override the current style:

       ```
   function OverrideTreeViewConstructedStyle() {
              try {
                  var treeItems = document.getElementsByClassName(".treeItemClass1")
                  if (treeItems != null & treeItems != undefined) {
                      var style = document.createElement('style')
                      style.innerHTML = '.content-region { font-size: 12px !important }'
                      if (document.querySelector('.treeItemClass1').shadowRoot != null && document.querySelector('.treeItemClass1').shadowRoot != undefined)
                          document.querySelector('.treeItemClass1').shadowRoot.appendChild(style);
                  }
              }
              catch
              {
          
              }
          }
```

**Is there any better way to override the style? Please guide. **
<img width="229" alt="image" src="https://user-images.githubusercontent.com/120010112/212859247-efd23a96-f3be-4603-873c-f71df7c3915d.png">

**Comment by Andras-Csanyi** [comment]
Hey, 

You can provide additional class or style to the [component](https://github.com/microsoft/fast-blazor/blob/2baa0b023f60af681e30f5f707f5d0cb6837c0f7/src/Microsoft.Fast.Components.FluentUI/Components/TreeView/FluentTreeView.razor#L6).

**Comment by V-AATARE** [comment]
![image](https://user-images.githubusercontent.com/120010112/212868139-461e4083-e2e3-48cc-b89a-9f94de80d5f9.png)
Thanks for 
I have done this, but not working. It's always picking up the styles from shadow element. I have used FAST Blazor component and passing the Class name.

**Comment by Andras-Csanyi** [comment]
Have you tried setting up the the custom class/style for the item itself? The link I sent you previously is for the tree component and not for the items.

**Comment by V-AATARE** [comment]
Yes,  Following is the code.
<FluentTreeItem Class="treeItemClass1">

**Comment by V-AATARE** [comment]
<FluentTreeItem Class="treeItemClass1">

**Comment by vnbaaij** [comment]
You should be able to target the `content-region` from css with the `::part(content-region)` selector. So if you have a component like this:

```
<div>
    <FluentTreeView @bind-CurrentSelected=currentSelected OnExpandedChange="HandleOnExpandedChanged">
        <FluentTreeItem Text="Root item 1">
            <FluentTreeItem Text="Flowers">
                <FluentTreeItem Disabled="true" Text="Daisy" />
                <FluentTreeItem Text="Sunflower" />
                <FluentTreeItem Text="Rose" />
            </FluentTreeItem>
            <FluentTreeItem Text="Nested item 2" />
            <FluentTreeItem Text="Nested item 3" />
        </FluentTreeItem>
        <FluentTreeItem Text="Root item 2">
            <FluentDivider></FluentDivider>
            <FluentTreeItem Text="Flowers">
                <FluentTreeItem Disabled="true" Text="Daisy" />
                <FluentTreeItem Text="Sunflower" />
                <FluentTreeItem Text="Rose" />
            </FluentTreeItem>
            <FluentTreeItem Text="Nested item 2" />
            <FluentTreeItem Text="Nested item 3" />
        </FluentTreeItem>
        <FluentTreeItem Text="Root item 3 - Leaf Erikson" />
    </FluentTreeView>
</div>
<p>Current selected tree item is @currentSelected?.Text</p>
<p>Current expanded/collapsed tree item is @currentAffected?.Text</p>

@code {
    FluentTreeItem? currentSelected;
    FluentTreeItem? currentAffected;

    private void HandleOnExpandedChanged(FluentTreeItem item)
    {
        currentAffected = item;
    }
}
```
And a scoped css like this:
```
::deep fluent-tree-item::part(content-region) {
    font-size: var(--type-ramp-plus-6-font-size);
}
```
_!!The enclosing div in the component is important for the ::deep selector to work!!_

You'll get this:
<img width="283" alt="image" src="https://user-images.githubusercontent.com/1761079/212887959-0a296b67-1e87-49d6-9be7-5a69d2ffbb84.png">
Of course, you can add more styling to the css

**Comment by V-AATARE** [comment]
It's working, Thanks.
