### ISSUE TITLE
feat: add PlaceHolder property to/in FluentSelect

### ISSUE THREAD

**Issue by BulldogCTISolutions** [microsoft/fast-blazor#312]
# 🙋 Feature Request

Add PlaceHolder property to FluentSelect.

## 🤔 Expected Behavior

Just like the PlaceHolder property for FluentCombobox

## 😯 Current Behavior

I have to add a string const as the first item and make sure in code that no one selects it.

**Comment by vnbaaij** [comment]
The `FluentSelect`'s underlying web component (fluent-select) does not support the concept of a placeholder and neither does a placeholder attribute exist for the <select> tag. As we wrap the web component, we also don't support this. Rolling your own solution for this is the way to go if you want this functionality.
