### ISSUE TITLE
docs: add implementation documentation for the Header on Fluent UI Web Components Website.

### ISSUE THREAD

**Issue by BulldogCTISolutions** [microsoft/fast-blazor#313]
# 🙋 Documentation Request

I'd love to know how y'all implemented the Header on the website.  Specifically, the Color picker and Theme options.  Yes, I would like to copy it for a non-public web assembly application.  I can see the FluentSelect, FluentOptions, but I cannot find the code-behind, nor css.

**Comment by vnbaaij** [comment]
It is all available in the `examples` folder here in the repo:
https://github.com/microsoft/fast-blazor/blob/main/examples/FluentUI.Demo.Shared/Shared/DemoMainLayout.razor
https://github.com/microsoft/fast-blazor/blob/main/examples/FluentUI.Demo.Shared/Shared/DemoMainLayout.css
