### ISSUE TITLE
DataGrid PropertyColumn Format throws  InvalidOperationException when DateTime column is nullable 

### ISSUE THREAD

**Issue by borisovalex** [microsoft/fast-blazor#314]
# 🐛 Bug Report

The following grid column works with nullable DateTime values:
<PropertyColumn Title="Last reviewed" Property="@(c => c.LastChangeReviewed)"   Sortable="true" Align="Align.Right" />

However, the following ...
<PropertyColumn Title="Last reviewed" Property="@(c => c.LastChangeReviewed)"   Format="yyyy-MM-dd" Sortable="true" Align="Align.Right" />

... throws the following exception:
InvalidOperationException: A 'Format' parameter was supplied, but the type 'System.Nullable`1[System.DateTime]' does not implement 'System.IFormattable'.
Microsoft.Fast.Components.FluentUI.PropertyColumn<TGridItem, TValue>.OnParametersSet() in PropertyColumn.cs, line 67

## 💻 Repro or Code Sample

Add PropertyColumn to FluentDataGrid for a nullable DateTime data source:
<PropertyColumn Property="@(p => p.NullableDateTime)" Title="Nullable DateTime" Format="dd-MMM-yyyy" Sortable="true" />

## 🤔 Expected Behavior

If the DateTime value is null, leave the cell empty. Expect code just need to check for null and if null do nothing.

## 😯 Current Behavior

An unhandled exception occurred while processing the request.
InvalidOperationException: A 'Format' parameter was supplied, but the type 'System.Nullable`1[System.DateTime]' does not implement 'System.IFormattable'.
Microsoft.Fast.Components.FluentUI.PropertyColumn<TGridItem, TValue>.OnParametersSet() in PropertyColumn.cs, line 67

## 💁 Possible Solution

The same issue was found in fixed in QuickGrid.
https://github.com/dotnet/aspnetcore/issues/42499

## 🌍 Your Environment

Microsoft.Fast.Components.FluentUI 2.0.4
Net 6.0

**Comment by vnbaaij** [comment]
Fixed in V2.0.5
