### ISSUE TITLE
fix: Clicking RadioGroup on Demo site results in NPE

### ISSUE THREAD

**Issue by BulldogCTISolutions** [microsoft/fast-blazor#316]
# 🐛 Bug Report

https://brave-cliff-0c0c93310.azurestaticapps.net/RadioGroup

## 😯 Current Behavior

![image](https://user-images.githubusercontent.com/50721551/217954738-d4c3aee0-7154-47b4-839c-ffa74dd0f395.png)

## 🔦 Context

I'm trying to understand why my radio buttons are not rendering as 'checked' when Checked="true".  I'm wondering if I need to encapsulate them within a RadioGroup.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by vnbaaij** [comment]
I'm pretty sure I had this working before. I'll take a look at it later on. In any case, you indeed need to put the radio components in a group. They can't function on their own.

**Comment by vnbaaij** [comment]
Fixed in V2.0.5
