### ISSUE TITLE
fix: RefreshDataAsync in DataGrid

### ISSUE THREAD

**Issue by datarit** [microsoft/fast-blazor#317]
In the DataGrid, using the GridItemsProvider, when calling the RefreshDataAsync method, the request operation is performed twice, resulting in unnecessary consumption of the API. Upon analyzing the code, I noticed that the RefreshDataAsync method simply calls another private method RefreshDataCoreAsync, and both of these methods have a call to StateHasChanged, causing the second API request to be unnecessary.

The issue is whether it is truly necessary for the RefreshDataAsync method to call StateHasChanged since RefreshDataCoreAsync already performs this call.

**Comment by BulldogCTISolutions** [comment]
@datarit, Does the RefreshDataAsync() work?  It refreshes your data?  I have Issue #311 where I update items in the source List<T>, but the grid isn't updating.  (I'm trying to swap rows in the grid).  Also have you tried SortByColumnAsync()?  If you don't mind, would you send me a snippet of your DataGrid and RefreshDataSync() call?  There aren't any examples in the interwebs for using FAST Fluent.

**Comment by datarit** [comment]
@BulldogCTISolutions Both RefreshDataAsync and SortByColumnAsync work and update the grid, in my case I'm using GridItemsProvider, so when I call one of the methods, they execute the request.
In OnInitializedAsync I configure the call to update the ItemsProvider:

`    private void SetItemsProvider()
    {
        rolesProvider = async req =>
        {
            try
            {
                roleQuery.SetSort(req.SortByColumn.ToString(), req.SortByAscending);
                roleQuery.SetOffset(req.StartIndex);

                var response = await _adminService.GetRolesAsync(roleQuery);
                if (RequestSuccess(response.Result))
                {
                    return GridItemsProviderResult.From(items: response.Roles, totalItemCount: (int)response.Result.Pagination.TotalRows);
                }
            }
            catch (Exception ex)
            {
                AddError(ex.Message);
            }
            return GridItemsProviderResult.From(items: new List<RoleView>(), totalItemCount: 0);

        };
    }`

and to update I simply call the RefreshDataAsync method

`    private async Task CreateRole()
    {
        try
        {
            var response = await _adminService.CreateRoleAsync(roleRequest);
            if (RequestSuccess(response.Result))
            {
                await grid.RefreshDataAsync();
            }
        }
        catch (Exception ex)
        {
            AddError(ex.Message);
        }
        ClosePanel();
    }`
in my case it executes the request 2 times, causing the grid to be updated 2 times.

**Comment by BulldogCTISolutions** [comment]
@datarit , you're amazing!  Switching to RowsDataProvider was the awesomesauce.  Thanks for sharing.  I didn't notice anything in  my code  that indicated RefreshDataAsync was refreshing the grid twice.  But my data source is a json file loaded into a List<T>.  (You wouldn't happen to know anything about FluentRadio #319 would you?)

**Comment by vnbaaij** [comment]
@BulldogCTISolutions I assume you're going to close #311 then? I'm looking into #319.
A fix for this one is about to be pushed/merged for next release

**Comment by vnbaaij** [comment]
Fixed in V2.0.5
