### ISSUE TITLE
feat: universal label style

### ISSUE THREAD

**Issue by idea-lei** [microsoft/fast-blazor#321]
# 🙋 Feature Request

Universal label style for form elements like FluentTextField, FluentSelect etc.

## 😯 Current Behavior

For FluentTextField element:
``` razor
<FluentTextField>Contact Email</FluentTextField>
```

![image](https://user-images.githubusercontent.com/30424884/218333652-c6e9a6df-5d4f-4436-aab4-cfba8c9231e2.png)

But for other elements like FluentSelect, you can not directly put the label between the tags. And if manually add the label tag, like FluentSelect, the style won't fit the one with FluentTextField.
``` razor
<label for="select_product">Select a product</label>
<FluentSelect Id="select_product" Items="products" OptionText="p=>p.Name" />
```
![image](https://user-images.githubusercontent.com/30424884/218333975-edabbcf5-7584-44d8-bd1f-ed235e2350b0.png)

## 💁 Possible Solution

I would suggest a new element "FluentLabel", instead of directly putting label between start-tag and end-tag since it could be confusing -- if you put text in p-tag, it will render the text as content rather than a label.

Another option would be attribute for label, like 
``` razor
<FluentSelect Label="Contact Email"></FluentSelect>
```

But this could be less customizable.

## 💻 Examples

[Angular Material Design](https://material.angular.io/components/form-field/overview)
``` html
<mat-form-field appearance="fill">
  <mat-label>Favorite food</mat-label>
  <mat-select>
    <mat-option *ngFor="let food of foods" [value]="food.value">
      {{food.viewValue}}
    </mat-option>
  </mat-select>
</mat-form-field>
```

**Comment by vnbaaij** [comment]
Hi,

This will be solved eventually in the underlying Web Components themselves (see for example https://github.com/microsoft/fast/issues/4801) and then trickle down to the Blazor components as well. We won't be adding any specific functionality for this here right now but are considering adding a component that can deliver this to the incubation lab. Happy to take a look at a PR for that! 

In the meantime, you can solve this by adding some CSS. In the demo I have this in the site.css:
```
label {
    display: block;
    color: var(--neutral-foreground-rest);
    font-family: var(--body-font);
    font-size: var(--type-ramp-base-font-size);
    line-height: var(--type-ramp-base-line-height);
    font-weight: initial;
    font-variation-settings: var(--type-ramp-base-font-variations);
    margin-inline-end: calc(var(--design-unit) * 2px + 2px);
    margin-bottom: 4px;
    cursor: pointer;
}
```
When applied to a form like this:
```
@page "/basicform-fluentui-components"
@using Microsoft.Extensions.Logging
@inject ILogger<BasicFormFluentUIComponents> Logger

<h1>Starfleet Starship Database</h1>

<h2>New Ship Entry Form</h2>

<EditForm Model="@starship" OnValidSubmit="@HandleValidSubmit">
    <DataAnnotationsValidator />
    <ValidationSummary />

    <div style="display:grid; gap: 5px;">
        <div><FluentTextField @bind-Value="starship.Identifier">Identifier:</FluentTextField></div>
        <div><FluentTextArea @bind-Value="starship.Description">Description (optional):</FluentTextArea></div>
        <div><label>Primary Classification:</label>
            <FluentSelect @bind-Value="starship.Classification" TOption="string">
                <FluentOption Value="">Select classification ...</FluentOption>
                <FluentOption Value="Exploration">Exploration</FluentOption>
                <FluentOption Value="Diplomacy">Diplomacy</FluentOption>
                <FluentOption Value="Defense">Defense</FluentOption>
            </FluentSelect>
        </div>
        <div><FluentNumberField @bind-Value="starship.MaximumAccommodation"> Maximum Accommodation:</FluentNumberField></div>
        <div><FluentCheckbox @bind-Value="starship.IsValidatedDesign">Engineering Approval</FluentCheckbox></div>
        <div><label>Production Date:</label>
            <FluentCalendar @bind-SelectedDates="prodDate" />
        </div>
        <div><FluentButton Type="ButtonType.Submit" Appearance="Appearance.Accent">Submit</FluentButton></div>
        <div><a href="http://www.startrek.com/">Star Trek</a>, ©1966-2019 CBS Studios, Inc. and <a href="https://www.paramount.com">Paramount Pictures</a></div>
    </div>
</EditForm>

@code {
    List<DateOnly> prodDate = new();

    protected override void OnInitialized()
    {
        prodDate.Add(new DateOnly(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day));
        starship.ProductionDate = prodDate[0];
    }

    private Starship starship = new();

    private void HandleValidSubmit()
    {
        Logger.LogInformation("HandleValidSubmit called");

        // Process the valid form
    }
}
```
You will get a consistent look like this:
<img width="251" alt="image" src="https://user-images.githubusercontent.com/1761079/218447065-a1c2dd5a-b957-4cea-a210-7b113a77eda7.png">

The labels which are placed inside the <Fluent...> components wilĺ not be affected by the site css as they have their own styling applied through the web component.

**Comment by bytefish** [comment]
@vnbaaij Thanks for your example. I also had a problem understanding how to apply labels to all elements within a form. Something like a FluentLabel would be great, like Angular does. It wasn’t clear to me, that Text between the tags get rendered as a label.

**Comment by vnbaaij** [comment]
We added FluentLabel for version 3: https://preview.fluentui-blazor.net/Label
________________________________

**Comment by bytefish** [comment]
@vnbaaij Noticed it the moment after commenting and deleted the comment. 😂 The new version has so many things I missed in previous versions. Great work. 👍

**Comment by vnbaaij** [comment]
Ah, that explains I couldn't find it... 😁
