### ISSUE TITLE
fix: Some vendor CSS files cannot be loaded (HTTP 400) in v2.1.0-rc3

### ISSUE THREAD

**Issue by ginomessmer** [microsoft/fast-blazor#325]
# 🐛 Bug Report

When we (@kirkone) upgraded to `v.2.1.0-rc3` from `2.0.5` by accident (supposed to upgrade to stable versions), we noticed that some CSS files that FAST Blazor uses cannot be loaded (HTTP 400). Because of that, the application won't fully start as seen in the screenshot below. We are not sure if this is the intended behavior since we have not followed any specific steps during the package update.

## 💻 Repro or Code Sample

0. Create a new project
1. Follow the README file to integrate the NuGet package
2. Update to pre-release version 2.1.0-rc3

## 🤔 Expected Behavior

- The dependency CSS assets should successfully load (HTTP 200)
- The application should load as expected
- The Blazor Fluent component should look as intended

## 😯 Current Behavior

- The Blazor application does not load successfully
### Browser Console Logs
```
reboot.css:1 
       
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
Microsoft.Fast.Components.FluentUI.bundle.scp.css:1 
       
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:7227/_content/Microsoft.Fast.Components.FluentUI/Microsoft.Fast.Components.FluentUI.lib.module.js:1 
        
      
       Failed to load resource: the server responded with a status of 404 (Not Found)
blazor.webassembly.js:1 
        
       TypeError: Failed to fetch dynamically imported module: https://localhost:7227/_content/Microsoft.Fast.Components.FluentUI/Microsoft.Fast.Components.FluentUI.lib.module.js
(anonymous) @ blazor.webassembly.js:1
reboot.css:1 
        
      
       Failed to load resource: the server responded with a status of 404 (Not Found)
Microsoft.Fast.Components.FluentUI.bundle.scp.css:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
DevTools failed to load source map: Could not load content for https://localhost:7227/StackContainer.razor.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

### Browser Screenshot

![Browser screenshot](https://user-images.githubusercontent.com/8465892/219622043-f017d39b-1b9f-45ae-865c-a67753c4281e.png)

### Debug Output

None related to the issue

## 💁 Possible Solution

Happy to share our source code information with you directly.

## 🔦 Context

While we upgraded all our packages to pre-release, we noticed that this package does not work as expected. We rolled back to the latest stable version (2.0.5).

## 🌍 Your Environment

* OS & Device: Windows 11
* Browser: Microsoft Edge Version 110.0.1587.49 (Official build) (64-bit)
* .NET 7.0 and FAST Version 2.1.0-rc3
* Blazor ASP.NET hosted server

**Comment by vnbaaij** [comment]
Yes, please give access to a repo/source. It seems some things are missing from the `index.html` file but can't tell what with this.

Could not reproduce this locally with a new and updated project.

**Comment by vnbaaij** [comment]
Further examination learned this was happening on a Server hosted application. A workaround (while we keep searching for a more permanent solution) is to install the package in the Server project as well.
