### ISSUE TITLE
Exception when building the rc3 nugget verison for prodution

### ISSUE THREAD

**Issue by chigivigi** [microsoft/fast-blazor#326]
# 🐛 Bug Report

I updated my project to use the newest nugget version rc3 so it can satisfy the need to use Icons and FluentNumberfield component inside the project. When running a yaml command for building the project for release environment it returns a exception. This did not happen for version 2.0.3 version.

## 💻 Repro or Code Sample

Create a Blazor WebAssembly project and install the 2.1.0-rc3 nugget.
Set the project file and Program.cs file as written in this link:
https://github.com/microsoft/fast-blazor/discussions/300#discussioncomment-4909264
We have a yaml file using .NET Core sdk version 6.0.0.x for building the project for release environment; the build command is: DotNetCoreCLI@2.

## 🤔 Expected Behavior

The build action should recognize that the ConfigurationGenerator class is part of the nugget package and be able to process the AddFluentUIComponents with a config consisting of GetIconConfiguration and GetEmojiConfiguration.

## 😯 Current Behavior

The build action does not recognize ConfigurationGenerator class and return the error message
Error CS0103: The name 'ConfigurationGenerator' does not exist in the current context.

## 🌍 Your Environment

Windows 11
Microsoft Edge latest version
Visual Studio 2022

**Comment by vnbaaij** [comment]
The `ConfigurationGenerator` is part of the NuGet package but as an ANALYZER ONLY. This means it will not be part of the distribution. Should work with the build command though.
I think I need a repo to see where this goes wrong. Have a link to check it out?

**Comment by vnbaaij** [comment]
.net6.0 or .net7.0 should not matter in that case. I'm using the DotNetCoreCLI@2 command in the package's workflow too. To build the demo site after generating the package. Maybe you can compare with the yaml files in the .github folder

**Comment by chigivigi** [comment]
The problem was solved after adding the UseDotNet@2 for net7.0 sdk inside the yaml file. Now the yaml file contains both the net6.0 and net7.0 UseDotNet@2 commands. The build for our project is successful now.

**Comment by NTimmons** [comment]
I am having the same issue.
.net7.0
Adding FluintUI to basic Blazor demo project

**Comment by vnbaaij** [comment]
Which version of the package are you trying to use?

**Comment by NTimmons** [comment]
2.3.6 I think...

**Comment by vnbaaij** [comment]
I'd compare it with the demo sites from the repository or install the template package and create a new site with that.

**Comment by ivanjx** [comment]
![image](https://github.com/microsoft/fluentui-blazor/assets/12814796/22cac5af-7da0-4025-9cce-48029ec2d40d)

`'LibraryConfiguration' does not contain a definition for 'IconConfiguration' and no accessible extension method 'IconConfiguration' accepting a first argument of type 'LibraryConfiguration' could be found`
`'LibraryConfiguration' does not contain a definition for 'EmojiConfiguration' and no accessible extension method 'EmojiConfiguration' accepting a first argument of type 'LibraryConfiguration' could be found`

version is 3.0.0-RC.1

**Comment by vnbaaij** [comment]
See https://preview.fluentui-blazor.net/UpgradeGuide
