### ISSUE TITLE
Not able to open combo box page 

### ISSUE THREAD

**Issue by anujans** [microsoft/fast-blazor#332]
Hi Team,

We are facing below issue on click of combo box on given url  https://brave-cliff-0c0c93310-259.centralus.azurestaticapps.net/Combobox .

<img width="911" alt="image" src="https://user-images.githubusercontent.com/120552820/221108167-ab24010c-47e5-4b93-b257-8faf463ff88b.png">

And is there any multiselect Combo box which can show all selected values even if that combo box is in collapsed state as below:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/120552820/221108854-fa5ffe18-f797-4711-b635-942c53903080.png">

Thank you in advance!!

**Comment by vnbaaij** [comment]
Hi,

The URL you should use for the stable version of the components demo is https://aka.ms/fluentui-blazor. The one you are referring to is a demo connected to a specific PR. It can show you the 'latest and greatest' but can also disappear at anytime. This PR in particular has just been merged into main and as a consequence the main demo is showing the error too 😲. I'll try to fix it asap.

The `<FluentCombobox>` allows you to either select a (one) value from the select list or type your own value. It does not support multiple selection.
