### ISSUE TITLE
fix: PublishFluentIconAssets not working in the v2.1 nuget package

### ISSUE THREAD

**Issue by jakupj** [microsoft/fast-blazor#333]
# 🐛 Bug Report

v2.1 of the nuget package are missing icons. Using the readme to include them throws an exception.

I tried to add it to my existing project but when using the datagrid that needs icons for the sort and filter indicator, it throws the following exception:

`Unhandled exception rendering component: The requested icon (ArrowSortUp, Size20, Regular) is not available in the collection
      System.ArgumentException: The requested icon (ArrowSortUp, Size20, Regular) is not available in the collection
         at Microsoft.Fast.Components.FluentUI.FluentIcon.OnInitialized() in /_/src/Microsoft.Fast.Components.FluentUI/Components/Icon/FluentIcon.cs:line 95
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()`

Seems the icons are not loaded. I tried to follow the latest what's new readme by adding the following to the project file:
`<PublishFluentIconAssets>true</PublishFluentIconAssets>`
`<PublishFluentEmojiAssets>true</PublishFluentEmojiAssets>`

But it still didn't work

I also create a new blazor server app using the provided templates and added  \<PublishFluentIconAssets\>true\</PublishFluentIconAssets\> along with the runtime check in program.cs eg:

`LibraryConfiguration config = new(ConfigurationGenerator.GetIconConfiguration(), ConfigurationGenerator.GetEmojiConfiguration());`
`builder.Services.AddFluentUIComponents(config);`

but it threw the exception below:

`System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.Fast.Components.FluentUI.Infrastructure.IStaticAssetService Lifetime: Scoped ImplementationType: Microsoft.Fast.Components.FluentUI.HttpBasedStaticAssetService': Unable to resolve service for type 'System.Net.Http.HttpClient' while attempting to activate 'Microsoft.Fast.Components.FluentUI.HttpBasedStaticAssetService'.)'`

**Comment by vnbaaij** [comment]
I think the second error could be solved by adding an HttpClient yourself first. In `Program.cs' add the line  `builder.Services.AddHttpClient();` before calling the `AddFluentUIComponets()`. Let me know if that works please. 

In the meantime, I'll work on the first error. Got a hunch but need to verify.

**Comment by jakupj** [comment]
Thanks that worked. 

But the datagrid only shows the up arrow when sorting in any direction. The demo site has the same behaviour

**Comment by vnbaaij** [comment]
I've added some text about the HttpClient to the readme. The arrow when sorting will be fixed in 2.1.1

**Comment by Marfusios** [comment]
Same issue here, even with 
```
<PublishFluentIconAssets>true</PublishFluentIconAssets>
<PublishFluentEmojiAssets>true</PublishFluentEmojiAssets>
```

it still breaks the application. 

A lot of errors: 

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The requested icon (CloudDismiss, Size24, Regular) is not available in the collection
System.ArgumentException: The requested icon (CloudDismiss, Size24, Regular) is not available in the collection
```

**Comment by vnbaaij** [comment]
Ok, found the missing icons issue. You need to change the code in `Program.cs` from
```
builder.Services.AddFluentUIComponents();
```
to 
```
LibraryConfiguration config = new(ConfigurationGenerator.GetIconConfiguration(), ConfigurationGenerator.GetEmojiConfiguration());
builder.Services.AddFluentUIComponents(config);
```
It is described in the blogpost but not in the what's new doc. Sorry, that's on me. I'll go add it now.

After you've made this change and visit the 'Query tool' page, you'll get a number of other errors. These need to be solved by binding each input derived component to a value. See the what's new and the blog for more information.

**Comment by Marfusios** [comment]
Thanks a lot! 
Will check it tomorrow
