### ISSUE TITLE
fix: RowIndex does not correspond to row position in FluentDataGrid

### ISSUE THREAD

**Issue by sagemodeninja** [microsoft/fast-blazor#336]
# 🐛 Bug Report

Goal:
Using `OnRowFocus`, get `RowIndex` and use it to determine the corresponding item of focused row.

Issue:
`RowIndex` returns the "wrong" value when navigating to and from another page.

## 💻 Repro or Code Sample

Repro: https://github.com/sagemodeninja/fdg-row-index

### Steps:
1. Run the repro code.
2. Open `Fetch Data`, and click on the rows.
3. Open `Another Fetch Data`, and click on the rows.
4. Go back to `Fetch Data`, click on any row, it should throw an exception.

## 🤔 Expected Behavior

Either `RowIndex` return a value that corresponds the the row's position on the grid or have another property do that specific function.

## 😯 Current Behavior

`RowIndex` value is based on an `internal static` counter that get's incremented on each new row.
This does not reset on new `FluentDataGrid` instances due to it's static nature.

## 💁 Possible Solution

If row indexes doesn't have to be unique across multiple grid instances, perhaps we could store the index counter on `InternalGridContext.cs`? This way we can still increment it's value but start from 0 on every new grid instance.

## 🔦 Context

I was trying to use `OnRowFocus` and get `RowIndex` and use it to determine the corresponding item of focused row.

## 🌍 Your Environment

* OS & Device: MacOS
* Browser: Apple Safari
* .NET and FAST Version: .NET 6 & v2.1.1

**Comment by vnbaaij** [comment]
This is fixed in V2.1.3. Will be on NuGet shortly. Thanks for reporting this (with excellent repo steps!)!
