### ISSUE TITLE
fix: Version 2.1.1 stops existing wasm project with server functioning.

### ISSUE THREAD

**Issue by AndyEdmonds** [microsoft/fast-blazor#339]
To reproduce: 
Create a standard Blazor Wasm app with server and windows authentication using the template.
Add version 2.1.1 via nuget
Add the project file change and program.cs changes as recommended to the client project.
result:
![image](https://user-images.githubusercontent.com/12613068/222753917-35eb0090-7a86-433e-a2ae-991f48ddf669.png)

Remove the project changes and revert to just:
```
            builder.Services.AddFluentUIComponents();
```
in the Program.cs and downgrade to version 2.05. The program runs as expected.

**Comment by vnbaaij** [comment]
We just had the exact same problem in another issue (#338). Fix for now seems to be to just install the package in the server project as well. No configuration changes needed.
I won't be at a pc and take a look at what is causing this until 2nd half of next week 🏝️
