### ISSUE TITLE
Error occurred in Icon Component in Microsoft.Fast.Components.FluentUI version 2.1.0 or later.

### ISSUE THREAD

**Issue by akvostar** [microsoft/fast-blazor#346]
Microsoft.Fast.Components.FluentUI version earlier works fine, but since version 2.1.0 the Icon component throws an error.

The browser throws the following error:

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The requested icon (ArrowCircleLeft, Size20, Regular) is not available in the collection
System.ArgumentException: The requested icon (ArrowCircleLeft, Size20, Regular) is not available in the collection
   at Microsoft.Fast.Components.FluentUI.FluentIcon.OnParametersSet() in /_/src/Microsoft.Fast.Components.FluentUI/Components/Icon/FluentIcon.cs:line 92
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

 ```html
<div style="display:flex">
    <FluentIcon Name="@FluentIcons.ArrowCircleLeft" />    
</div>
```

**Comment by vnbaaij** [comment]
Did you see this: https://github.com/microsoft/fast-blazor#when-upgrading-from-an-earlier-version or this: https://github.com/microsoft/fast-blazor/blob/main/WHATSNEW.md or this: https://baaijte.net/blog/whats-new-in-the-microsoft-fluent-ui-library-for-blazor-version-21/
