### ISSUE TITLE
Skeleton sample error: Cannot read property 'querySelectorAll' of null

### ISSUE THREAD

**Issue by danroth27** [microsoft/fast-blazor#35]
Repro steps:

- Run the FluentUIServerSample
- Select the web components
- Select the Skeleton link

Error in the browser console:

```
onloadwff.js:71 Uncaught (in promise) TypeError: Cannot read property 'querySelectorAll' of null
    at s.<anonymous> (onloadwff.js:71)
    at l (onloadwff.js:71)
    at Object.next (onloadwff.js:71)
    at n (onloadwff.js:71)
```

**Comment by EisenbergEffect** [comment]
@EddyHaigh Do you think this is another LastPass-related issue?

**Comment by EddyHaigh** [comment]
@EisenbergEffect yeah, I'm not getting any errors on the skeleton test when last pass is disabled/not installed. Its also coming from the same onloadwff.js.

**Comment by EisenbergEffect** [comment]
Thanks for the confirmation @EddyHaigh !
