### ISSUE TITLE
Yellow active link color is unreadable on white background

### ISSUE THREAD

**Issue by danroth27** [microsoft/fast-blazor#38]
Repro steps:

- Run the FluentUIServerSample
- Select the web components
- Click on a component link
- Try to read the yellow active link in yellow on a white background 😆

**Comment by awentzel** [comment]
Does this seem like it may be an issue with FAST itself?  @nicholasrice can you confirm?  If so, we could open a new issue on FAST and link this too it?  Thoughts?

**Comment by nicholasrice** [comment]
Yea my understanding is that the yellow comes from Blazor itself, but there may be work we can do to align that color to the components?

**Comment by danroth27** [comment]
With the updated sample app styling, this no longer seems to be an issue. I'm guessing the original yellow coloring came from https://github.com/microsoft/fast-blazor/blob/main/examples/FluentUIServerSample/wwwroot/site.css#L8.

**Comment by nicholasrice** [comment]
Ahh yep, I replaced the anchors with `fluent-anchor` which doesn't use the Blazor "active" selector. Cool I think we can close this then.
