### ISSUE TITLE
feat: add automated publishing with Beachball for package versions

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast-blazor#55]
# 🙋 Feature Request
Packages should be automated, generate release changelogs, and publish with auto bumping.

## 🤔 Expected Behavior
Improved publishing autonomy.

## 😯 Current Behavior
N/A

## 💁 Possible Solution
Beachball could be used and would be consistent with other FAST repositories.

**Comment by vnbaaij** [comment]
This doesn't work for NuGet packages unfortunately.
