### ISSUE TITLE
NavLinkFluentAnchor forces to reload the page as if it were a regular anchor tag

### ISSUE THREAD

**Issue by EddyHaigh** [microsoft/fast-blazor#57]
# 🐛 Bug Report

When using the `NavLinkFluentAnchor` the `Href` forces to reload the page as if it were a regular anchor tag. Breadcrumb item links work fine but NavLinkFluentAnchor doesn't?

## 💻 Repro or Code Sample

Have two routable pages and have a `NavLinkFluentAnchor` linking between the pages.

## 🤔 Expected Behavior

Clicking a `NavLinkFluentAnchor` changes page **without** with a SPA like transition.

## 😯 Current Behavior

Clicking a `NavLinkFluentAnchor` performs a network request to the linked page.

## 💁 Possible Solution

Could be related to the shadow DOM used by the fluent-anchor.

## 🔦 Context

Can't provide the best UX when using `NavLinkFluentAnchor` and have to style own NavLink.

## 🌍 Your Environment

* Windows 10
* Microsoft Edge and Chrome
* .Net 5.0.6 and Microsoft.Fast.Components.FluentUI 0.2.0

**Comment by EisenbergEffect** [comment]
This seems like it could be an issue with Blazor's router not using composedPath() to check event sources for navigation scenarios. @EddyHaigh Can you confirm that this is happening with a Blazor router setup?

**Comment by ShreyasJejurkar** [comment]
Am trying to reproduce this bug, but am not able to find the component in library! Is there anything am missing? 

![image](https://user-images.githubusercontent.com/17148381/142764145-c634ef88-bdff-4b99-9793-a3929a06ca8a.png)

**Comment by EddyHaigh** [comment]
It was a component in the 0.2 version, and it looks like the component no longer exists, probably still worth looking to see if the FluentAnchor works; if so, then I think this issue should be closed.

**Comment by ShreyasJejurkar** [comment]
I tried with the following markup and it works great and as usual. No separate network request. 

![image](https://user-images.githubusercontent.com/17148381/142764668-1a64613e-8915-409b-a1b0-389fec017988.png)
