### ISSUE TITLE
Question: why FluentInputBase.cs and not Blazor's InputBase.cs?

### ISSUE THREAD

**Issue by dmoncada** [microsoft/fast-blazor#58]
Just found out about the existence of this package today. I think it's pretty cool as it makes it simpler to adopt the FAST Fluent components in a Blazor project 😃.

Navigating through the code it came to my attention the fact that all input-like components (for ex. `FluentTextField`) derive from a `FluentInputBase.cs` ([link][f-input-base]), which is almost an exact, line-by-line duplicate of Blazor's `InputBase.cs` ([link][input-base]) base class for input elements. I was wondering what was the reason for this divergence? Is the plan to eventually make all input components in this package derive from the latter?

[f-input-base]: https://github.com/microsoft/fast-blazor/blob/main/src/Microsoft.Fast.Components.FluentUI/FluentInputBase.cs
[input-base]: https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Forms/InputBase.cs

**Comment by EisenbergEffect** [comment]
That's a good question. We had help from the Blazor team on this, and I'm not sure why they made that decision. @javiercn Can you share some thinking around this decision? We'd like to try to do the most Blazor-like thing we can here so it makes as much sense to the community as possible.

**Comment by javiercn** [comment]
InputBase requires an `EditContext` to work, and we didn't want to place that limitation on the fluent inputs, so I "butchered" the base class and updated it to avoid needing an edit context.

This is something I think we can change in Blazor if we have to so that fluent can leverage InputBase directly.

**Comment by EisenbergEffect** [comment]
I think it would be nice if we could leverage that. However, I don't know the implications of EditContext and associated infrastructure. So, I couldn't comment on the recommended refactoring. Keep us in the loop if you re-work some of that and we're happy to switch our components over to the new base class.

**Comment by vnbaaij** [comment]
With .NET 6 the requirement for an EditContext is no longer there (https://github.com/dotnet/aspnetcore/commit/afacc8740c40bf465da9b9a34914a2d88d243b3c). We should change to derive from InputBase

**Comment by EisenbergEffect** [comment]
Closing this since I think we answered the question. We can revisit code changes at a later point based on future Blazor releases.
