### ISSUE TITLE
feat: add support for netstandard2.1

### ISSUE THREAD

**Issue by markdav-is** [microsoft/fast-blazor#60]
# 🙋 Feature Request

we are building a blazor wasm app in netcore31 and are interested in fast-blazor that is currently targeted net50.  I made a [fork](https://github.com/markdav-is/fast-blazor-31/tree/feature/dotnet31) that compiles and targets the earlier framework, but when I run it, it silently fails to render the controls, and messes up the page layout.  I'm not sure its worth the trouble to support this edge-case, but we should would appreciate it. 

## 🤔 Expected Behavior

support for netsttandard2.1 WASM net core 3.1 would be exactly like net50 support

## 😯 Current Behavior

The controls don't render with style applied and the page payout gets borked.  (see image in comments below)

## 💁 Possible Solution

check out my [fork](https://github.com/markdav-is/fast-blazor-31/tree/feature/dotnet31) and see that simply downgrading the framework is not enough. to get it to render.  I've added a new sample to this fork as well.

## 🔦 Context

We are looking at white-label solutions for our apps and think building fast design systems might be a good solution.

## 💻 Examples

see image in Comments

**Comment by markdav-is** [comment]
here's an example of the page payout changes that happen when you target netstandard2.1

![image](https://user-images.githubusercontent.com/311063/122135126-c245ca00-cdf4-11eb-9feb-bc967b7c09ec.png)

**Comment by markdav-is** [comment]
I was able to get fast-blazor to compile targeting netstandard2.1  https://github.com/markdav-is/fast-blazor-31/tree/feature/dotnet31

**Comment by EisenbergEffect** [comment]
Closing this. I don't think we're going to be able to support older versions of .NET.
