### ISSUE TITLE
feat: expose .show() and .hide() functionality. in FluentDialog

### ISSUE THREAD

**Issue by markdav-is** [microsoft/fast-blazor#62]
# 🙋 Feature Request
expose .show() and .hide() functionality. in FluentDialog

## 🤔 Expected Behavior

being able to call  .show() and .hide() methods in FluentDialog blazor control
## 😯 Current Behavior
today you have to play around with the hidden attribute to get the dialog to pop. That's OK, but it would be handy to call the underlying web component.

## 💁 Possible Solution

use JS INterop to call the underlying  .show() and .hide() functionality. in FluentDialog

## 🔦 Context

I have a load dialog I'm trying to pop when a button is pressed.

## 💻 Examples

https://gist.github.com/EddyHaigh/639a2b28d542a7e416bd484e7187867a

**Comment by EisenbergEffect** [comment]
We're definitely open to adding JS Interop where it makes sense. This seems like a good case for that. @markdav-is Are you interested in putting together a pull request for this? We'd be happy to work with you to get it in. My team hasn't done any JS Interop work with Blazor yet, so this could also help us learn a bit from the community.

**Comment by markdav-is** [comment]
I can do that.  I'm on deadline for the next few days, but I'm excited to contribute next week.  Should be a very minor PR.

**Comment by EisenbergEffect** [comment]
No rush! We'd love to have your contribution whenever you can get around to it 😄
