### ISSUE TITLE
feat: improve project structure

### ISSUE THREAD

**Issue by emimontesdeoca** [microsoft/fast-blazor#64]
# 🙋 Feature Request

I'd like to work on a PR to improve the project structure, it would make the development process easier for other developers. Also this will help to add more features like `fluent-data-grid` which needs JS Interop that needs a javascript file attached to that component.

Overall changes proposed would be to have each component to have its folder, a `bundlconfig.json` file, `Enums`, `Extensions` and other utilities to be located in separated folders.

## 🤔 Expected Behavior

The expected behavior would be to have a better experience as a developer when working in this project, with everything separated.

## 😯 Current Behavior

Right now the project has all the componentes under the `Components` folder, each component has its code in the same `razor` file. It also has all the extensions, enums, utilities, etc under the same folder, which could end up being a mess.

## 💁 Possible Solution

I'd gathered a couple of ideas on how it could be improved.

### Each components to have its folder

In order to have better separation between the components, I'd suggest we have a folder inside `Components` folder, that contains the components name. This will allow the developers to add isolated Javascript and CSS, instead of maybe adding it under a wwwroot folder.

This is an example on how it would for the component `FluentDialog`:

```
Microsoft.Fast.Components.FluentUI/
├── Components/
	├── FluentDialog/
	     ├── FluentDialog.razor
	     ├── FluentDialog.razor.cs
	     ├── FluentDialog.razor.js
	     ├── FluentDialog.razor.css
```

### Include `@fluentui/web-components` in the `wwwroot` folder

Create the new `wwwroot` folder and add the `@fluentui/web-components` javascript file in there to keep what version is there instead of always having the latest one, it could introduce breaking changes that this project components do not support.

### Bundling and minification with `bundleconfig.json` file

Also after the project start to have javascript files, it should be added a `bundleconfig.json` that links all the components javascript files into one place.

This is an example of `bundleconfig.json` file that would generate minified and bundled `js` and `css` file that would be stored at `wwwroot/*`:

```json
[
  {
    "outputFileName": "wwwroot/css/fluent-ui-blazor.bundle.min.css",
    "inputFiles": [
      "Components/FluentDialog/FluentDialog.razor.cs.css"
    ]
  },
  {
    "outputFileName": "wwwroot/js/fluent-ui-blazor.bundle.min.js",
    "inputFiles": [
      "wwwroot/lib/fluentui/web-components.min.js",
      "Components/FluentDialog/FluentDialog.razor.cs.js"
    ],
    "minify": {
      "enabled": true,
      "renameLocals": true
    }
  }
]
```

### Create `Enums` folder

Move all the `Enums` that there's in the project inside a `Enums` folder, it would help to have everything in one place.

```
Microsoft.Fast.Components.FluentUI/
├── Enums/
	├── Appearance.cs
	├── Autocomplete.cs
	├── Position.cs
	├── Direction
	├── ExpandMode
	├── Orientation
	├── Resize
	├── Shape
```

### Create `Extensions` folder

Move all the `Enums` that there's in the project inside a `Enums` folder, it would help to have everything in one place.

```
Microsoft.Fast.Components.FluentUI/
├── Extensions/
	├── Appearance.cs
	├── Autocomplete.cs
	├── Position.cs
	├── Direction
	├── ExpandMode
	├── Orientation
	├── Resize
	├── Shape
```

### Update `README.md`

With these new changes, the [Getting Started](https://github.com/microsoft/fast-blazor#getting-started) would become obsolete, since we now have files, we would have to update the guide to reference them.

## 🔦 Context

I think improving the overall project structure will help the developers.

## 💻 Examples

Examples have been aded on the possible solution part.

## Checklist

I'd say that this is the checklist this request to be completely done:
- [ ] Each component on its folder with all extra files
- [ ] Enums on different folder
- [ ] Extensions on different folder
- [ ] Bundling and minification
- [ ] Add `@fluentui/web-components` files in the project
- [ ] Update all references on `FluenUIServerSample`
- [ ] Update documentation

**Comment by EisenbergEffect** [comment]
I can definitely see re-organizing the components. I think I'd like to keep the enum and associated extensions together if possible. Can you share a bit about what the use cases are for css and js in this project? I can't see us adding css, as that is contained in the core web components themselves. What about JS? Is that for interop scenarios?

**Comment by emimontesdeoca** [comment]
Defnitely CSS it's not going to be needed, but JS interop is probably going to be since some of the components logic just work better if you call them using JS Interop.

I'm going to make a pull request so the changes can be seen.

**Comment by EisenbergEffect** [comment]
@emimontesdeoca That sounds good. Maybe make a small PR to just change one or two components so we can take a look. There are a couple of other component PR updates in progress, which we may need to get merged first. So, it might be better to use your PR purely as an example with the idea that we may need to do a separate PR later for the actual change.

**Comment by emimontesdeoca** [comment]
@EisenbergEffect I've been busy these weeks, I'll try to have the PR done by this weekend 😊!

**Comment by EisenbergEffect** [comment]
Sounds great. We understand the business ;) We've had a lot going on as well. Thanks for working with us!

**Comment by EisenbergEffect** [comment]
I'm going to close this for now. We're certainly welcome to improvements to the project structure in the future whenever time/interest permits.
