### ISSUE TITLE
rfc: fast-blazor absent from blazor.net UI Component section

### ISSUE THREAD

**Issue by zc0rp10** [microsoft/fast-blazor#66]
# 💬 RFC

There's a number of commercial UI and Component libraries listed on [blazor.net](https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor) while there's no mention of [microsoft/fast-blazor](https://github.com/microsoft/fast-blazor). Surely just an oversight, I thought I'd mention.

## 🔦 Context

See the UI component ecosystem section of blazor.net -> Seem's like a lot of people new to Blazor are not finding their way here and are instead lead astray since there's no mention of this great free alternative for base components in their applications.

## 💻 Examples

![image](https://user-images.githubusercontent.com/55206983/126530633-964cb58f-fb28-4677-8f79-1924da5c1938.png)

**Comment by vnbaaij** [comment]
Fixed by https://github.com/AdrienTorris/awesome-blazor/pull/543

**Comment by vnbaaij** [comment]
Fixed by https://github.com/AdrienTorris/awesome-blazor/pull/543
