### ISSUE TITLE
feat: Missing lot of components from Fluent UI

### ISSUE THREAD

**Issue by zoran123456** [microsoft/fast-blazor#73]
# 🙋 Feature Request

Hi! So this "fast.design" is more of a generic frontend web framework, which also includes some components from Fluent UI?
I'm having problems understanding the difference between fast.design and fluent UI.

https://developer.microsoft.com/en-us/fluentui#/

I noticed in the examples, a lot of components are missing in fast.design, for instance, Avatar component, Rating, Command Bar, Ribbon Menu, etc. So I don't know what are we supposed to do with those components? I am using "BlazorFluentUI" and it does work quite well (although it has bugs), with all controls from Fluent UI supported, but I would really prefer to go with the official MS framework. 

Can we expect to have additional (all!) components in the future, or shall we treat fast.design framework as something not entirely focused on the Fluent UI (more like a separate, generic "one size fits them all" framework)?

Thank you.

**Comment by EisenbergEffect** [comment]
Command Bar has been added as Toolbar. Avatar and Rating are in development. I think we should close this in lieu of having individual component requests opened on the main repo. That will help us to figure out what to build next.

**Comment by EisenbergEffect** [comment]
For future reference, please make requests for individual components here: https://github.com/microsoft/fast If you specifically want it as a FluentUI components, please add that detail to the request (since our team maintains more than one design system). Thank you!
