### ISSUE TITLE
FluentNumberField not working in WASM

### ISSUE THREAD

**Issue by chigivigi** [microsoft/fast-blazor#87]
# 🐛 Bug Report

I have a wasm project where I am testing fast-blazor components. The page breaks when containing FluentNumberField component.

## 💻 Repro or Code Sample
I have copied the code from the data grid example

```
<h2>Grid with RowItemTemplate</h2>
<Microsoft.Fast.Components.FluentUI.FluentDataGrid id="defaultGrid3" RowsData=RowsGrid1 ColumnDefinitions=ColumnsGrid1 GridTemplateColumns="1fr 1fr">
    <RowItemTemplate>
        <Microsoft.Fast.Components.FluentUI.FluentDataGridRow TItem=SampleGrid1Data>
            <Microsoft.Fast.Components.FluentUI.FluentDataGridCell GridColumn=1>
                <Microsoft.Fast.Components.FluentUI.FluentTextField @bind-Value=@context.Name></Microsoft.Fast.Components.FluentUI.FluentTextField>
            </Microsoft.Fast.Components.FluentUI.FluentDataGridCell>
             <Microsoft.Fast.Components.FluentUI.FluentDataGridCell GridColumn=2>
                <Microsoft.Fast.Components.FluentUI.FluentNumberField @bind-Value=@context.Age></Microsoft.Fast.Components.FluentUI.FluentNumberField>
            </Microsoft.Fast.Components.FluentUI.FluentDataGridCell>           

        </Microsoft.Fast.Components.FluentUI.FluentDataGridRow>
    </RowItemTemplate>
</Microsoft.Fast.Components.FluentUI.FluentDataGrid>
```

## 🤔 Expected Behavior
I should be able to display the value and change it.

## 😯 Current Behavior
The column is not showing,
It breaks with the error message: crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: no idea on how to unbox value types
      Error: no idea on how to unbox value types
 
## 💁 Possible Solution
I do not have a suggestion how to fix it.

## 🔦 Context
We are testing this nuget package with the intention to change our frontend application to use it.

## 🌍 Your Environment
I am working on Windows 10 PC.
The browser I am using is Microsoft Edge Version 94.0.992.38.
The nuget package version I am using is 0.4.0.
The project is net5.0 blazor Wasm.

**Comment by EisenbergEffect** [comment]
Looks like we've got a fix under review for this in the main repo: https://github.com/microsoft/fast/pull/5289
