### ISSUE TITLE
feat: add Template for ListBox/ComboBox

### ISSUE THREAD

**Issue by flogruber** [microsoft/fast-blazor#939]
# 🙋 Feature Request

## 🤔 Expected Behavior

It would be great if you could define a template for the `Option<T>` entries in the listbox and combobox.  
So that you can customize the entry in the listbox and combobox more.  

## 💁 Possible Solution

```
public class Person
{
  public string ID { get; set; }
  public string FirstName { get; set; }
  public string LastName { get; set; }
}
```

```
<FluentListbox Items=@_person 
               OptionValue="@(i => i.ID)" >
  <FluentItemTemplate>
     <FluentIcon Icon="Icons.Regular.Size16.Delete" Slot="end" OnClick="@(() => _persons.Remove(item))" />
     @item.FirstName / @item.LastName
  </FluentItemTemplate>
</FluentListbox>

@code {
  private List<Person> _persons = new List<Person>();
}
```

**Comment by vnbaaij** [comment]
Hi,

We are in a bit of a feature freeze now till after the v4 release (next weet at .NET Conf (fingers crossed)). After that we will reist this and see if we can implement it.
